/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Answer extends org.jooq.impl.TableImpl<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord> {

	private static final long serialVersionUID = 981179864;

	/**
	 * The singleton instance of <code>adviceexchange.answer</code>
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.Answer ANSWER = new com.dozortsev.adviceexchange.domain.jooq.tables.Answer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord> getRecordType() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord.class;
	}

	/**
	 * The column <code>adviceexchange.answer.asw_id</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, java.lang.Integer> ASW_ID = createField("asw_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.answer.asw_question_id</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, java.lang.Integer> ASW_QUESTION_ID = createField("asw_question_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.answer.asw_votes</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, java.lang.Integer> ASW_VOTES = createField("asw_votes", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>adviceexchange.answer.asw_accepted</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, java.lang.Byte> ASW_ACCEPTED = createField("asw_accepted", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>adviceexchange.answer</code> table reference
	 */
	public Answer() {
		this("answer", null);
	}

	/**
	 * Create an aliased <code>adviceexchange.answer</code> table reference
	 */
	public Answer(java.lang.String alias) {
		this(alias, com.dozortsev.adviceexchange.domain.jooq.tables.Answer.ANSWER);
	}

	private Answer(java.lang.String alias, org.jooq.Table<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord> aliased) {
		this(alias, aliased, null);
	}

	private Answer(java.lang.String alias, org.jooq.Table<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.dozortsev.adviceexchange.domain.jooq.Adviceexchange.ADVICEEXCHANGE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, java.lang.Integer> getIdentity() {
		return com.dozortsev.adviceexchange.domain.jooq.Keys.IDENTITY_ANSWER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord> getPrimaryKey() {
		return com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_ANSWER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord>>asList(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_ANSWER_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_ANSWER_ID, com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_ANSWER_ASW_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, ?>>asList(com.dozortsev.adviceexchange.domain.jooq.Keys.FK_ASW_ID, com.dozortsev.adviceexchange.domain.jooq.Keys.FK_ASW_QS_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.dozortsev.adviceexchange.domain.jooq.tables.Answer as(java.lang.String alias) {
		return new com.dozortsev.adviceexchange.domain.jooq.tables.Answer(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.dozortsev.adviceexchange.domain.jooq.tables.Answer rename(java.lang.String name) {
		return new com.dozortsev.adviceexchange.domain.jooq.tables.Answer(name, null);
	}
}
