/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAnswer extends org.jooq.impl.TableImpl<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord> {

	private static final long serialVersionUID = -1893846375;

	/**
	 * The singleton instance of <code>adviceexchange.answer</code>
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer ANSWER = new com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord> getRecordType() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord.class;
	}

	/**
	 * The column <code>adviceexchange.answer.id</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.answer.qt_id</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, java.lang.Integer> QT_ID = createField("qt_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.answer.accepted</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, java.lang.Byte> ACCEPTED = createField("accepted", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>adviceexchange.answer</code> table reference
	 */
	public TAnswer() {
		this("answer", null);
	}

	/**
	 * Create an aliased <code>adviceexchange.answer</code> table reference
	 */
	public TAnswer(java.lang.String alias) {
		this(alias, com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER);
	}

	private TAnswer(java.lang.String alias, org.jooq.Table<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord> aliased) {
		this(alias, aliased, null);
	}

	private TAnswer(java.lang.String alias, org.jooq.Table<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.dozortsev.adviceexchange.domain.jooq.Adviceexchange.ADVICEEXCHANGE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, java.lang.Integer> getIdentity() {
		return com.dozortsev.adviceexchange.domain.jooq.Keys.IDENTITY_ANSWER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord> getPrimaryKey() {
		return com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_ANSWER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord>>asList(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_ANSWER_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_ANSWER_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, ?>>asList(com.dozortsev.adviceexchange.domain.jooq.Keys.FK_ASW_ID, com.dozortsev.adviceexchange.domain.jooq.Keys.FK_ASW_QS_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer as(java.lang.String alias) {
		return new com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer rename(java.lang.String name) {
		return new com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer(name, null);
	}
}
