/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTag extends org.jooq.impl.TableImpl<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord> {

	private static final long serialVersionUID = -707904789;

	/**
	 * The singleton instance of <code>adviceexchange.tag</code>
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.TTag TAG = new com.dozortsev.adviceexchange.domain.jooq.tables.TTag();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord> getRecordType() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord.class;
	}

	/**
	 * The column <code>adviceexchange.tag.id</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.tag.name</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.tag.desc</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord, java.lang.String> DESC = createField("desc", org.jooq.impl.SQLDataType.CLOB.length(65535).nullable(false), this, "");

	/**
	 * Create a <code>adviceexchange.tag</code> table reference
	 */
	public TTag() {
		this("tag", null);
	}

	/**
	 * Create an aliased <code>adviceexchange.tag</code> table reference
	 */
	public TTag(java.lang.String alias) {
		this(alias, com.dozortsev.adviceexchange.domain.jooq.tables.TTag.TAG);
	}

	private TTag(java.lang.String alias, org.jooq.Table<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord> aliased) {
		this(alias, aliased, null);
	}

	private TTag(java.lang.String alias, org.jooq.Table<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.dozortsev.adviceexchange.domain.jooq.Adviceexchange.ADVICEEXCHANGE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord, java.lang.Integer> getIdentity() {
		return com.dozortsev.adviceexchange.domain.jooq.Keys.IDENTITY_TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord> getPrimaryKey() {
		return com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_TAG_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord>>asList(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_TAG_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_TAG_ID, com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_TAG_NAME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.dozortsev.adviceexchange.domain.jooq.tables.TTag as(java.lang.String alias) {
		return new com.dozortsev.adviceexchange.domain.jooq.tables.TTag(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.dozortsev.adviceexchange.domain.jooq.tables.TTag rename(java.lang.String name) {
		return new com.dozortsev.adviceexchange.domain.jooq.tables.TTag(name, null);
	}
}
