/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TVote extends org.jooq.impl.TableImpl<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord> {

	private static final long serialVersionUID = -1889889753;

	/**
	 * The singleton instance of <code>adviceexchange.vote</code>
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.TVote VOTE = new com.dozortsev.adviceexchange.domain.jooq.tables.TVote();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord> getRecordType() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord.class;
	}

	/**
	 * The column <code>adviceexchange.vote.id</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.vote.user_id</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.vote.activity_id</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord, java.lang.Integer> ACTIVITY_ID = createField("activity_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.vote.score</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord, java.lang.Integer> SCORE = createField("score", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.vote.created</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>adviceexchange.vote</code> table reference
	 */
	public TVote() {
		this("vote", null);
	}

	/**
	 * Create an aliased <code>adviceexchange.vote</code> table reference
	 */
	public TVote(java.lang.String alias) {
		this(alias, com.dozortsev.adviceexchange.domain.jooq.tables.TVote.VOTE);
	}

	private TVote(java.lang.String alias, org.jooq.Table<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord> aliased) {
		this(alias, aliased, null);
	}

	private TVote(java.lang.String alias, org.jooq.Table<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.dozortsev.adviceexchange.domain.jooq.Adviceexchange.ADVICEEXCHANGE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord, java.lang.Integer> getIdentity() {
		return com.dozortsev.adviceexchange.domain.jooq.Keys.IDENTITY_VOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord> getPrimaryKey() {
		return com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_VOTE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord>>asList(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_VOTE_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_VOTE_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord, ?>>asList(com.dozortsev.adviceexchange.domain.jooq.Keys.FK_VT_USER_ID, com.dozortsev.adviceexchange.domain.jooq.Keys.FK_VT_ACTIVITY_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.dozortsev.adviceexchange.domain.jooq.tables.TVote as(java.lang.String alias) {
		return new com.dozortsev.adviceexchange.domain.jooq.tables.TVote(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.dozortsev.adviceexchange.domain.jooq.tables.TVote rename(java.lang.String name) {
		return new com.dozortsev.adviceexchange.domain.jooq.tables.TVote(name, null);
	}
}
