/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends org.jooq.impl.TableImpl<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> {

	private static final long serialVersionUID = 1510184539;

	/**
	 * The singleton instance of <code>adviceexchange.user</code>
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.User USER = new com.dozortsev.adviceexchange.domain.jooq.tables.User();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> getRecordType() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord.class;
	}

	/**
	 * The column <code>adviceexchange.user.id</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.user.name</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.user.age</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.Integer> AGE = createField("age", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>adviceexchange.user.about_me</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.String> ABOUT_ME = createField("about_me", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>adviceexchange.user.joined</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.sql.Timestamp> JOINED = createField("joined", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>adviceexchange.user.location</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.String> LOCATION = createField("location", org.jooq.impl.SQLDataType.VARCHAR.length(120), this, "");

	/**
	 * The column <code>adviceexchange.user.site</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.String> SITE = createField("site", org.jooq.impl.SQLDataType.VARCHAR.length(70), this, "");

	/**
	 * The column <code>adviceexchange.user.email</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.user.password</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.user.enabled</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.Byte> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>adviceexchange.user.reputation</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.Integer> REPUTATION = createField("reputation", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>adviceexchange.user</code> table reference
	 */
	public User() {
		this("user", null);
	}

	/**
	 * Create an aliased <code>adviceexchange.user</code> table reference
	 */
	public User(java.lang.String alias) {
		this(alias, com.dozortsev.adviceexchange.domain.jooq.tables.User.USER);
	}

	private User(java.lang.String alias, org.jooq.Table<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> aliased) {
		this(alias, aliased, null);
	}

	private User(java.lang.String alias, org.jooq.Table<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.dozortsev.adviceexchange.domain.jooq.Adviceexchange.ADVICEEXCHANGE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.Integer> getIdentity() {
		return com.dozortsev.adviceexchange.domain.jooq.Keys.IDENTITY_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> getPrimaryKey() {
		return com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord>>asList(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_ID, com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_EMAIL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.dozortsev.adviceexchange.domain.jooq.tables.User as(java.lang.String alias) {
		return new com.dozortsev.adviceexchange.domain.jooq.tables.User(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.dozortsev.adviceexchange.domain.jooq.tables.User rename(java.lang.String name) {
		return new com.dozortsev.adviceexchange.domain.jooq.tables.User(name, null);
	}
}
