/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserActivity extends org.jooq.impl.TableImpl<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> {

	private static final long serialVersionUID = -1180925410;

	/**
	 * The singleton instance of <code>adviceexchange.user_activity</code>
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity USER_ACTIVITY = new com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> getRecordType() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord.class;
	}

	/**
	 * The column <code>adviceexchange.user_activity.ua_id</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord, java.lang.Integer> UA_ID = createField("ua_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.user_activity.ua_type</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord, java.lang.String> UA_TYPE = createField("ua_type", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.user_activity.ua_user_id</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord, java.lang.Integer> UA_USER_ID = createField("ua_user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.user_activity.ua_content</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord, java.lang.String> UA_CONTENT = createField("ua_content", org.jooq.impl.SQLDataType.CLOB.length(65535).nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.user_activity.ua_active</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord, java.lang.Byte> UA_ACTIVE = createField("ua_active", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>adviceexchange.user_activity.ua_created</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord, java.sql.Timestamp> UA_CREATED = createField("ua_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>adviceexchange.user_activity</code> table reference
	 */
	public UserActivity() {
		this("user_activity", null);
	}

	/**
	 * Create an aliased <code>adviceexchange.user_activity</code> table reference
	 */
	public UserActivity(java.lang.String alias) {
		this(alias, com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY);
	}

	private UserActivity(java.lang.String alias, org.jooq.Table<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserActivity(java.lang.String alias, org.jooq.Table<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.dozortsev.adviceexchange.domain.jooq.Adviceexchange.ADVICEEXCHANGE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord, java.lang.Integer> getIdentity() {
		return com.dozortsev.adviceexchange.domain.jooq.Keys.IDENTITY_USER_ACTIVITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> getPrimaryKey() {
		return com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_ACTIVITY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord>>asList(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_ACTIVITY_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_ACTIVITY_UA_ID, com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_ACTIVITY_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord, ?>>asList(com.dozortsev.adviceexchange.domain.jooq.Keys.FK_UA_USER_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity as(java.lang.String alias) {
		return new com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity rename(java.lang.String name) {
		return new com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity(name, null);
	}
}
