/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends org.jooq.impl.TableImpl<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> {

	private static final long serialVersionUID = -1014471310;

	/**
	 * The singleton instance of <code>adviceexchange.user</code>
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.User USER = new com.dozortsev.adviceexchange.domain.jooq.tables.User();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> getRecordType() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord.class;
	}

	/**
	 * The column <code>adviceexchange.user.user_id</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.user.user_name</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.String> USER_NAME = createField("user_name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.user.user_age</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.Integer> USER_AGE = createField("user_age", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>adviceexchange.user.user_about_me</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.String> USER_ABOUT_ME = createField("user_about_me", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>adviceexchange.user.user_joined</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.sql.Timestamp> USER_JOINED = createField("user_joined", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>adviceexchange.user.user_location</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.String> USER_LOCATION = createField("user_location", org.jooq.impl.SQLDataType.VARCHAR.length(120), this, "");

	/**
	 * The column <code>adviceexchange.user.user_site</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.String> USER_SITE = createField("user_site", org.jooq.impl.SQLDataType.VARCHAR.length(70), this, "");

	/**
	 * The column <code>adviceexchange.user.user_email</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.String> USER_EMAIL = createField("user_email", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.user.user_password</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.String> USER_PASSWORD = createField("user_password", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>adviceexchange.user.user_enabled</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.Byte> USER_ENABLED = createField("user_enabled", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>adviceexchange.user.user_reputation</code>.
	 */
	public final org.jooq.TableField<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.Integer> USER_REPUTATION = createField("user_reputation", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>adviceexchange.user</code> table reference
	 */
	public User() {
		this("user", null);
	}

	/**
	 * Create an aliased <code>adviceexchange.user</code> table reference
	 */
	public User(java.lang.String alias) {
		this(alias, com.dozortsev.adviceexchange.domain.jooq.tables.User.USER);
	}

	private User(java.lang.String alias, org.jooq.Table<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> aliased) {
		this(alias, aliased, null);
	}

	private User(java.lang.String alias, org.jooq.Table<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.dozortsev.adviceexchange.domain.jooq.Adviceexchange.ADVICEEXCHANGE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.Integer> getIdentity() {
		return com.dozortsev.adviceexchange.domain.jooq.Keys.IDENTITY_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> getPrimaryKey() {
		return com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord>>asList(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_USER_ID, com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_ID, com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_USER_EMAIL, com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_EMAIL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.dozortsev.adviceexchange.domain.jooq.tables.User as(java.lang.String alias) {
		return new com.dozortsev.adviceexchange.domain.jooq.tables.User(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.dozortsev.adviceexchange.domain.jooq.tables.User rename(java.lang.String name) {
		return new com.dozortsev.adviceexchange.domain.jooq.tables.User(name, null);
	}
}
