/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Adviceexchange extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -826235804;

	/**
	 * The singleton instance of <code>adviceexchange</code>
	 */
	public static final Adviceexchange ADVICEEXCHANGE = new Adviceexchange();

	/**
	 * No further instances allowed
	 */
	private Adviceexchange() {
		super("adviceexchange");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER,
			com.dozortsev.adviceexchange.domain.jooq.tables.TBadge.BADGE,
			com.dozortsev.adviceexchange.domain.jooq.tables.TComment.COMMENT,
			com.dozortsev.adviceexchange.domain.jooq.tables.TQuestion.QUESTION,
			com.dozortsev.adviceexchange.domain.jooq.tables.TQuestionTag.QUESTION_TAG,
			com.dozortsev.adviceexchange.domain.jooq.tables.TTag.TAG,
			com.dozortsev.adviceexchange.domain.jooq.tables.TUser.USER,
			com.dozortsev.adviceexchange.domain.jooq.tables.TUserActivity.USER_ACTIVITY,
			com.dozortsev.adviceexchange.domain.jooq.tables.TUserBadge.USER_BADGE,
			com.dozortsev.adviceexchange.domain.jooq.tables.TVote.VOTE);
	}
}
