/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Adviceexchange extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1310931429;

	/**
	 * The singleton instance of <code>adviceexchange</code>
	 */
	public static final Adviceexchange ADVICEEXCHANGE = new Adviceexchange();

	/**
	 * No further instances allowed
	 */
	private Adviceexchange() {
		super("adviceexchange");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.dozortsev.adviceexchange.domain.jooq.tables.Answer.ANSWER,
			com.dozortsev.adviceexchange.domain.jooq.tables.Badge.BADGE,
			com.dozortsev.adviceexchange.domain.jooq.tables.Comment.COMMENT,
			com.dozortsev.adviceexchange.domain.jooq.tables.Question.QUESTION,
			com.dozortsev.adviceexchange.domain.jooq.tables.QuestionTag.QUESTION_TAG,
			com.dozortsev.adviceexchange.domain.jooq.tables.Tag.TAG,
			com.dozortsev.adviceexchange.domain.jooq.tables.User.USER,
			com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY,
			com.dozortsev.adviceexchange.domain.jooq.tables.UserBadge.USER_BADGE);
	}
}
