/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>adviceexchange</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, java.lang.Integer> IDENTITY_ANSWER = Identities0.IDENTITY_ANSWER;
	public static final org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.BadgeRecord, java.lang.Integer> IDENTITY_BADGE = Identities0.IDENTITY_BADGE;
	public static final org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.CommentRecord, java.lang.Integer> IDENTITY_COMMENT = Identities0.IDENTITY_COMMENT;
	public static final org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionRecord, java.lang.Integer> IDENTITY_QUESTION = Identities0.IDENTITY_QUESTION;
	public static final org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord, java.lang.Integer> IDENTITY_TAG = Identities0.IDENTITY_TAG;
	public static final org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.Integer> IDENTITY_USER = Identities0.IDENTITY_USER;
	public static final org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord, java.lang.Integer> IDENTITY_USER_ACTIVITY = Identities0.IDENTITY_USER_ACTIVITY;
	public static final org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord, java.lang.Integer> IDENTITY_VOTE = Identities0.IDENTITY_VOTE;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord> KEY_ANSWER_PRIMARY = UniqueKeys0.KEY_ANSWER_PRIMARY;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord> KEY_ANSWER_ID = UniqueKeys0.KEY_ANSWER_ID;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.BadgeRecord> KEY_BADGE_PRIMARY = UniqueKeys0.KEY_BADGE_PRIMARY;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.BadgeRecord> KEY_BADGE_ID = UniqueKeys0.KEY_BADGE_ID;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.BadgeRecord> KEY_BADGE_NAME = UniqueKeys0.KEY_BADGE_NAME;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.CommentRecord> KEY_COMMENT_PRIMARY = UniqueKeys0.KEY_COMMENT_PRIMARY;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.CommentRecord> KEY_COMMENT_ID = UniqueKeys0.KEY_COMMENT_ID;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionRecord> KEY_QUESTION_PRIMARY = UniqueKeys0.KEY_QUESTION_PRIMARY;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionRecord> KEY_QUESTION_ID = UniqueKeys0.KEY_QUESTION_ID;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord> KEY_TAG_PRIMARY = UniqueKeys0.KEY_TAG_PRIMARY;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord> KEY_TAG_ID = UniqueKeys0.KEY_TAG_ID;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord> KEY_TAG_NAME = UniqueKeys0.KEY_TAG_NAME;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> KEY_USER_ID = UniqueKeys0.KEY_USER_ID;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> KEY_USER_EMAIL = UniqueKeys0.KEY_USER_EMAIL;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> KEY_USER_ACTIVITY_PRIMARY = UniqueKeys0.KEY_USER_ACTIVITY_PRIMARY;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> KEY_USER_ACTIVITY_ID = UniqueKeys0.KEY_USER_ACTIVITY_ID;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord> KEY_VOTE_PRIMARY = UniqueKeys0.KEY_VOTE_PRIMARY;
	public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord> KEY_VOTE_ID = UniqueKeys0.KEY_VOTE_ID;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> FK_ASW_ID = ForeignKeys0.FK_ASW_ID;
	public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionRecord> FK_ASW_QS_ID = ForeignKeys0.FK_ASW_QS_ID;
	public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.CommentRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> FK_CM_ID = ForeignKeys0.FK_CM_ID;
	public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.CommentRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionRecord> FK_CM_QUESTION_ID = ForeignKeys0.FK_CM_QUESTION_ID;
	public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> FK_QS_ID = ForeignKeys0.FK_QS_ID;
	public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionTagRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionRecord> FK_QT_QUESTION_ID = ForeignKeys0.FK_QT_QUESTION_ID;
	public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionTagRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord> FK_QT_TAG_ID = ForeignKeys0.FK_QT_TAG_ID;
	public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> FK_UA_USER_ID = ForeignKeys0.FK_UA_USER_ID;
	public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserBadgeRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.BadgeRecord> FK_UB_BADGE_ID = ForeignKeys0.FK_UB_BADGE_ID;
	public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserBadgeRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> FK_UB_USER_ID = ForeignKeys0.FK_UB_USER_ID;
	public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> FK_VT_USER_ID = ForeignKeys0.FK_VT_USER_ID;
	public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> FK_VT_ACTIVITY_ID = ForeignKeys0.FK_VT_ACTIVITY_ID;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, java.lang.Integer> IDENTITY_ANSWER = createIdentity(com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER, com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER.ID);
		public static org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.BadgeRecord, java.lang.Integer> IDENTITY_BADGE = createIdentity(com.dozortsev.adviceexchange.domain.jooq.tables.TBadge.BADGE, com.dozortsev.adviceexchange.domain.jooq.tables.TBadge.BADGE.ID);
		public static org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.CommentRecord, java.lang.Integer> IDENTITY_COMMENT = createIdentity(com.dozortsev.adviceexchange.domain.jooq.tables.TComment.COMMENT, com.dozortsev.adviceexchange.domain.jooq.tables.TComment.COMMENT.ID);
		public static org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionRecord, java.lang.Integer> IDENTITY_QUESTION = createIdentity(com.dozortsev.adviceexchange.domain.jooq.tables.TQuestion.QUESTION, com.dozortsev.adviceexchange.domain.jooq.tables.TQuestion.QUESTION.ID);
		public static org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord, java.lang.Integer> IDENTITY_TAG = createIdentity(com.dozortsev.adviceexchange.domain.jooq.tables.TTag.TAG, com.dozortsev.adviceexchange.domain.jooq.tables.TTag.TAG.ID);
		public static org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord, java.lang.Integer> IDENTITY_USER = createIdentity(com.dozortsev.adviceexchange.domain.jooq.tables.TUser.USER, com.dozortsev.adviceexchange.domain.jooq.tables.TUser.USER.ID);
		public static org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord, java.lang.Integer> IDENTITY_USER_ACTIVITY = createIdentity(com.dozortsev.adviceexchange.domain.jooq.tables.TUserActivity.USER_ACTIVITY, com.dozortsev.adviceexchange.domain.jooq.tables.TUserActivity.USER_ACTIVITY.ID);
		public static org.jooq.Identity<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord, java.lang.Integer> IDENTITY_VOTE = createIdentity(com.dozortsev.adviceexchange.domain.jooq.tables.TVote.VOTE, com.dozortsev.adviceexchange.domain.jooq.tables.TVote.VOTE.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord> KEY_ANSWER_PRIMARY = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER, com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER.ID);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord> KEY_ANSWER_ID = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER, com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER.ID);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.BadgeRecord> KEY_BADGE_PRIMARY = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TBadge.BADGE, com.dozortsev.adviceexchange.domain.jooq.tables.TBadge.BADGE.ID);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.BadgeRecord> KEY_BADGE_ID = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TBadge.BADGE, com.dozortsev.adviceexchange.domain.jooq.tables.TBadge.BADGE.ID);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.BadgeRecord> KEY_BADGE_NAME = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TBadge.BADGE, com.dozortsev.adviceexchange.domain.jooq.tables.TBadge.BADGE.NAME);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.CommentRecord> KEY_COMMENT_PRIMARY = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TComment.COMMENT, com.dozortsev.adviceexchange.domain.jooq.tables.TComment.COMMENT.ID);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.CommentRecord> KEY_COMMENT_ID = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TComment.COMMENT, com.dozortsev.adviceexchange.domain.jooq.tables.TComment.COMMENT.ID);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionRecord> KEY_QUESTION_PRIMARY = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TQuestion.QUESTION, com.dozortsev.adviceexchange.domain.jooq.tables.TQuestion.QUESTION.ID);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionRecord> KEY_QUESTION_ID = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TQuestion.QUESTION, com.dozortsev.adviceexchange.domain.jooq.tables.TQuestion.QUESTION.ID);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord> KEY_TAG_PRIMARY = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TTag.TAG, com.dozortsev.adviceexchange.domain.jooq.tables.TTag.TAG.ID);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord> KEY_TAG_ID = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TTag.TAG, com.dozortsev.adviceexchange.domain.jooq.tables.TTag.TAG.ID);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord> KEY_TAG_NAME = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TTag.TAG, com.dozortsev.adviceexchange.domain.jooq.tables.TTag.TAG.NAME);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> KEY_USER_PRIMARY = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TUser.USER, com.dozortsev.adviceexchange.domain.jooq.tables.TUser.USER.ID);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> KEY_USER_ID = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TUser.USER, com.dozortsev.adviceexchange.domain.jooq.tables.TUser.USER.ID);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> KEY_USER_EMAIL = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TUser.USER, com.dozortsev.adviceexchange.domain.jooq.tables.TUser.USER.EMAIL);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> KEY_USER_ACTIVITY_PRIMARY = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TUserActivity.USER_ACTIVITY, com.dozortsev.adviceexchange.domain.jooq.tables.TUserActivity.USER_ACTIVITY.ID);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> KEY_USER_ACTIVITY_ID = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TUserActivity.USER_ACTIVITY, com.dozortsev.adviceexchange.domain.jooq.tables.TUserActivity.USER_ACTIVITY.ID);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord> KEY_VOTE_PRIMARY = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TVote.VOTE, com.dozortsev.adviceexchange.domain.jooq.tables.TVote.VOTE.ID);
		public static final org.jooq.UniqueKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord> KEY_VOTE_ID = createUniqueKey(com.dozortsev.adviceexchange.domain.jooq.tables.TVote.VOTE, com.dozortsev.adviceexchange.domain.jooq.tables.TVote.VOTE.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> FK_ASW_ID = createForeignKey(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_ACTIVITY_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER, com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER.ID);
		public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionRecord> FK_ASW_QS_ID = createForeignKey(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_QUESTION_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER, com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER.QT_ID);
		public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.CommentRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> FK_CM_ID = createForeignKey(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_ACTIVITY_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.tables.TComment.COMMENT, com.dozortsev.adviceexchange.domain.jooq.tables.TComment.COMMENT.ID);
		public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.CommentRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionRecord> FK_CM_QUESTION_ID = createForeignKey(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_QUESTION_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.tables.TComment.COMMENT, com.dozortsev.adviceexchange.domain.jooq.tables.TComment.COMMENT.QT_ID);
		public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> FK_QS_ID = createForeignKey(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_ACTIVITY_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.tables.TQuestion.QUESTION, com.dozortsev.adviceexchange.domain.jooq.tables.TQuestion.QUESTION.ID);
		public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionTagRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionRecord> FK_QT_QUESTION_ID = createForeignKey(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_QUESTION_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.tables.TQuestionTag.QUESTION_TAG, com.dozortsev.adviceexchange.domain.jooq.tables.TQuestionTag.QUESTION_TAG.QT_ID);
		public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.QuestionTagRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.TagRecord> FK_QT_TAG_ID = createForeignKey(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_TAG_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.tables.TQuestionTag.QUESTION_TAG, com.dozortsev.adviceexchange.domain.jooq.tables.TQuestionTag.QUESTION_TAG.TAG_ID);
		public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> FK_UA_USER_ID = createForeignKey(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.tables.TUserActivity.USER_ACTIVITY, com.dozortsev.adviceexchange.domain.jooq.tables.TUserActivity.USER_ACTIVITY.USER_ID);
		public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserBadgeRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.BadgeRecord> FK_UB_BADGE_ID = createForeignKey(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_BADGE_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.tables.TUserBadge.USER_BADGE, com.dozortsev.adviceexchange.domain.jooq.tables.TUserBadge.USER_BADGE.BADGE_ID);
		public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserBadgeRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> FK_UB_USER_ID = createForeignKey(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.tables.TUserBadge.USER_BADGE, com.dozortsev.adviceexchange.domain.jooq.tables.TUserBadge.USER_BADGE.USER_ID);
		public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> FK_VT_USER_ID = createForeignKey(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.tables.TVote.VOTE, com.dozortsev.adviceexchange.domain.jooq.tables.TVote.VOTE.USER_ID);
		public static final org.jooq.ForeignKey<com.dozortsev.adviceexchange.domain.jooq.tables.records.VoteRecord, com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> FK_VT_ACTIVITY_ID = createForeignKey(com.dozortsev.adviceexchange.domain.jooq.Keys.KEY_USER_ACTIVITY_PRIMARY, com.dozortsev.adviceexchange.domain.jooq.tables.TVote.VOTE, com.dozortsev.adviceexchange.domain.jooq.tables.TVote.VOTE.ACTIVITY_ID);
	}
}
