/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in adviceexchange
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table adviceexchange.answer
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer ANSWER = com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER;

	/**
	 * The table adviceexchange.badge
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.TBadge BADGE = com.dozortsev.adviceexchange.domain.jooq.tables.TBadge.BADGE;

	/**
	 * The table adviceexchange.comment
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.TComment COMMENT = com.dozortsev.adviceexchange.domain.jooq.tables.TComment.COMMENT;

	/**
	 * The table adviceexchange.question
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.TQuestion QUESTION = com.dozortsev.adviceexchange.domain.jooq.tables.TQuestion.QUESTION;

	/**
	 * The table adviceexchange.question_tag
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.TQuestionTag QUESTION_TAG = com.dozortsev.adviceexchange.domain.jooq.tables.TQuestionTag.QUESTION_TAG;

	/**
	 * The table adviceexchange.tag
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.TTag TAG = com.dozortsev.adviceexchange.domain.jooq.tables.TTag.TAG;

	/**
	 * The table adviceexchange.user
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.TUser USER = com.dozortsev.adviceexchange.domain.jooq.tables.TUser.USER;

	/**
	 * The table adviceexchange.user_activity
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.TUserActivity USER_ACTIVITY = com.dozortsev.adviceexchange.domain.jooq.tables.TUserActivity.USER_ACTIVITY;

	/**
	 * The table adviceexchange.user_badge
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.TUserBadge USER_BADGE = com.dozortsev.adviceexchange.domain.jooq.tables.TUserBadge.USER_BADGE;

	/**
	 * The table adviceexchange.vote
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.TVote VOTE = com.dozortsev.adviceexchange.domain.jooq.tables.TVote.VOTE;
}
