/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in adviceexchange
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table adviceexchange.answer
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.Answer ANSWER = com.dozortsev.adviceexchange.domain.jooq.tables.Answer.ANSWER;

	/**
	 * The table adviceexchange.badge
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.Badge BADGE = com.dozortsev.adviceexchange.domain.jooq.tables.Badge.BADGE;

	/**
	 * The table adviceexchange.comment
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.Comment COMMENT = com.dozortsev.adviceexchange.domain.jooq.tables.Comment.COMMENT;

	/**
	 * The table adviceexchange.question
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.Question QUESTION = com.dozortsev.adviceexchange.domain.jooq.tables.Question.QUESTION;

	/**
	 * The table adviceexchange.question_tag
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.QuestionTag QUESTION_TAG = com.dozortsev.adviceexchange.domain.jooq.tables.QuestionTag.QUESTION_TAG;

	/**
	 * The table adviceexchange.tag
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.Tag TAG = com.dozortsev.adviceexchange.domain.jooq.tables.Tag.TAG;

	/**
	 * The table adviceexchange.user
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.User USER = com.dozortsev.adviceexchange.domain.jooq.tables.User.USER;

	/**
	 * The table adviceexchange.user_activity
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity USER_ACTIVITY = com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY;

	/**
	 * The table adviceexchange.user_badge
	 */
	public static final com.dozortsev.adviceexchange.domain.jooq.tables.UserBadge USER_BADGE = com.dozortsev.adviceexchange.domain.jooq.tables.UserBadge.USER_BADGE;
}
