
  /* Badge data */

INSERT INTO badge (bdg_id, bdg_name, bdg_desc)
VALUES
  (1, 'Admin', 'One who oversees discussions on an Internet forum'),
  (2, 'User', 'A person using a generic system');

  /* User data */

INSERT INTO user (user_id, user_name, user_age, user_location, user_email, user_password, user_reputation) VALUES

  (1, 'Ross Oconnor', 24, 'Ulloa (Barrial)', 'sed.dui.Fusce@torquentperconubia.net', 341442, 9471),
  (2, 'Stone Davis', 20, 'Renlies', 'Mauris.vestibulum@convallis.org', 296400, 3795),
  (3, 'Henry Mcmahon', 41, 'Valera Fratta', 'vitae.aliquet.nec@inconsequat.edu', 779347, 6946),
  (4, 'Honorato Manning', 17, 'Arendonk', 'pede.Suspendisse.dui@malesuada.org', 424781, 1185),
  (5, 'Joshua Foley', 28, 'Penna San Giovanni', 'enim.Sed.nulla@magnis.ca', 982360, 3001),
  (6, 'Merrill Cotton', 38, 'St. Davids', 'enim.nisl@pulvinararcuet.org', 576987, 4259),
  (7, 'Kelly Singleton', 46, 'Mannheim', 'aliquet.vel@temporest.co.uk', 300125, 9370),
  (8, 'Herman Cabrera', 49, 'Landenne', 'consectetuer.adipiscing.elit@liberoMorbiaccumsan.ca', 225793, 8475),
  (9, 'Gannon Patterson', 18, 'Albi', 'risus@accumsan.com', 634194, 5473),
  (10, 'Finn Burris', 37, 'Sint-Stevens-Woluwe', 'adipiscing.Mauris@Fuscealiquetmagna.net', 159980, 5616),
  (11, 'Brett Ferrell', 36, 'Watford', 'ut.dolor@etmagnisdis.ca', 553748, 2892),
  (12, 'Sawyer Lynn', 44, 'Cropalati', 'mauris.erat.eget@Nunc.edu', 94548, 5272),
  (13, 'Reuben Washington', 41, 'Hattiesburg', 'nunc.interdum@et.net', 504951, 9286),
  (14, 'Deacon Craft', 48, 'Sint-Pieters-Kapelle', 'velit.Sed@risusvariusorci.co.uk', 361091, 5734),
  (15, 'Drew Mejia', 16, 'Le Havre', 'rhoncus.Donec.est@enimCurabitur.org', 737307, 7579),
  (16, 'Levi Swanson', 35, 'Warspite', 'semper.Nam.tempor@penatibus.ca', 925535, 3059),
  (17, 'Brett Kaufman', 42, 'Ruette', 'Nulla.semper.tellus@et.edu', 399319, 1731),
  (18, 'Rogan Dennis', 48, 'Caloundra', 'convallis.convallis@congueaaliquet.co.uk', 715399, 1191),
  (19, 'Walter Castro', 35, 'Milwaukee', 'Nunc.sed.orci@velit.edu', 104172, 8551),
  (20, 'Maxwell Haley', 27, 'Lamontzï¿½e', 'malesuada.vel@iaculisenimsit.edu', 488557, 9892),
  (21, 'Kevin Strong', 48, 'Caplan', 'lobortis.Class@sit.org', 396577, 3816),
  (22, 'Oren Hopper', 16, 'Fuenlabrada', 'tellus@mollisnec.edu', 490178, 6230),
  (23, 'Fritz Ballard', 19, 'Qu?bec City', 'consectetuer.mauris@ultriciessem.edu', 41803, 7871),
  (24, 'Aristotle Castillo', 19, 'Naninne', 'purus@bibendum.edu', 815124, 3652),
  (25, 'Charles Foreman', 29, 'Hattiesburg', 'diam.luctus.lobortis@nonummyultricies.ca', 766777, 509),
  (26, 'Hunter Houston', 33, 'Tracadie-Shelia', 'magnis.dis@velarcueu.co.uk', 577094, 2292),
  (27, 'Rahim Ayala', 44, 'Wieze', 'dui@liberomauris.edu', 406370, 3923),
  (28, 'Phillip Snyder', 36, 'Kaaskerke', 'accumsan@adipiscingelitEtiam.edu', 769786, 5405),
  (29, 'Coby Banks', 42, 'Talence', 'Cras.convallis@diamSeddiam.com', 963775, 5685),
  (30, 'Timon Rhodes', 46, 'Kruibeke', 'scelerisque.lorem@ultricies.edu', 640118, 8009),
  (31, 'Deacon Mclaughlin', 39, 'Leamington', 'pede.sagittis.augue@sem.org', 702999, 5491),
  (32, 'Rafael Stanley', 34, 'Weston-super-Mare', 'quis.tristique.ac@euduiCum.net', 146414, 2796),
  (33, 'Mason Hodges', 47, 'Lawton', 'Morbi@lacus.co.uk', 550428, 9346),
  (34, 'Fulton Rosario', 27, 'Eisden', 'lectus.ante@enim.co.uk', 685561, 6084),
  (35, 'Kamal Maxwell', 30, 'Hospitalet de Llobregat', 'Vestibulum@Duisa.net', 121871, 3526),
  (36, 'Luke Kirkland', 23, 'Andalo', 'neque.vitae@Nulla.org', 946911, 9501),
  (37, 'Solomon Reeves', 49, 'Kilwinning', 'aliquet.odio.Etiam@lobortisquam.org', 364177, 4939),
  (38, 'Tanek Lambert', 31, 'Saint-Marcel', 'vestibulum@augueeutellus.ca', 476209, 2296),
  (39, 'Patrick Buck', 27, 'Baltimore', 'facilisis.magna.tellus@ut.ca', 805328, 9965),
  (40, 'Drake Ochoa', 44, 'Hay River', 'bibendum@massanon.net', 510093, 3564),
  (41, 'Alfonso Chen', 50, 'Wondelgem', 'Curabitur@idblanditat.net', 987740, 1068),
  (42, 'Quinn Skinner', 20, 'Anderlecht', 'dictum@fermentummetus.co.uk', 327315, 2473),
  (43, 'Tyrone Mullen', 20, 'Wanaka', 'volutpat.Nulla.facilisis@fringilla.co.uk', 527740, 4297),
  (44, 'Isaiah Jensen', 33, 'Wellingborough', 'eu@enimnectempus.org', 749092, 8812),
  (45, 'Kennedy Trevino', 48, 'Leers-et-Fosteau', 'non@erategettincidunt.org', 251530, 7514),
  (46, 'Chaim Mcguire', 32, 'Sale', 'nisl.Maecenas.malesuada@Aliquam.edu', 235279, 9800),
  (47, 'Martin Price', 40, 'Lebach', 'et.nunc.Quisque@Phasellusdolorelit.net', 875540, 8614),
  (48, 'Tobias Key', 37, 'Bischofshofen', 'pellentesque.Sed@feugiat.co.uk', 976908, 5748),
  (49, 'Vernon Massey', 27, 'Gelsenkirchen', 'ipsum.dolor.sit@mollisInteger.net', 870561, 6137),
  (50, 'Gray Rosario', 41, 'Silverton', 'libero@inaliquetlobortis.ca', 119838, 4025),
  (51, 'Aaron Vasquez', 19, 'Hatfield', 'odio.Phasellus@lacus.edu', 809505, 3923),
  (52, 'Theodore Beach', 31, 'Orvault', 'mauris@pedeNuncsed.edu', 337314, 7437),
  (53, 'Tanner Mccullough', 25, 'Villa Cortese', 'et@Cras.co.uk', 854068, 8345),
  (54, 'Gray Sweeney', 15, 'Rebecq', 'erat.nonummy@Nullamlobortisquam.org', 187759, 2490),
  (55, 'Cameron Stevenson', 30, 'Rhisnes', 'ornare@semperduilectus.edu', 233514, 5592),
  (56, 'Lyle Patel', 48, 'Cirencester', 'Cras.interdum.Nunc@nullaIntegerurna.ca', 694740, 3988),
  (57, 'Adam Thompson', 24, 'Boechout', 'ipsum.primis@Proinsed.ca', 735265, 2347),
  (58, 'Arden Barry', 40, 'Vespolate', 'felis.orci.adipiscing@IntegermollisInteger.edu', 487273, 3632),
  (59, 'Gabriel Pate', 26, 'Dumfries', 'Duis.mi@a.edu', 405548, 4467),
  (60, 'Carlos Ford', 35, 'Picture Butte', 'lectus@ligulatortordictum.org', 925851, 9126),
  (61, 'Nolan Lane', 16, 'Castiglione a Casauria', 'aliquam@elitsedconsequat.co.uk', 683141, 2450),
  (62, 'Valentine Alvarez', 26, 'Krems an der Donau', 'nec.cursus@etmagnisdis.org', 30609, 5394),
  (63, 'Preston Mcclure', 46, 'Dunstable', 'orci@idrisusquis.com', 858888, 6660),
  (64, 'Wing Randolph', 45, 'Saint-RhÃ©my-en-Bosses', 'eu.eros.Nam@vitaealiquetnec.net', 153471, 7449),
  (65, 'Neil Berg', 44, 'College', 'ante@pede.com', 855939, 2661),
  (66, 'Reese Wilson', 37, 'Kitimat', 'erat.volutpat@imperdietnecleo.ca', 161592, 3319),
  (67, 'Kibo Barlow', 48, 'Kessenich', 'ac.ipsum.Phasellus@temporaugue.ca', 143825, 2122),
  (68, 'Arthur Atkinson', 48, 'Santa Maria a Monte', 'sit.amet@malesuadaaugueut.org', 459580, 6765),
  (69, 'Zachery Barron', 22, 'Verdun', 'nec.eleifend@vehicula.ca', 117098, 8221),
  (70, 'Oren Bender', 37, 'Liverpool', 'amet.luctus.vulputate@vehiculaaliquetlibero.org', 47034, 8776),
  (71, 'Steven Austin', 35, 'Amsterdam', 'eget.metus@diam.org', 248441, 2508),
  (72, 'James Randall', 20, 'Billings', 'luctus.vulputate@in.net', 847599, 2147),
  (73, 'Jeremy Turner', 33, 'Tranent', 'aliquet.vel@erosnonenim.co.uk', 374756, 8050),
  (74, 'Troy Little', 41, 'Steendorp', 'montes.nascetur.ridiculus@acarcu.edu', 410520, 4737),
  (75, 'Hamilton Franklin', 25, 'Toulouse', 'In@dolornonummyac.ca', 196385, 2215),
  (76, 'Isaiah Bowen', 39, 'Heusden', 'tellus.Aenean.egestas@magnisdisparturient.co.uk', 606721, 8810),
  (77, 'Laith Patton', 42, 'Spaniards Bay', 'nibh.Donec.est@facilisisloremtristique.org', 742473, 2668),
  (78, 'Jonas Meyers', 19, 'Medicine Hat', 'morbi.tristique@ultrices.ca', 380903, 1177),
  (79, 'Kenneth Joyner', 18, 'Tenby', 'Quisque.porttitor@perinceptos.net', 748594, 584),
  (80, 'Valentine Vang', 21, 'Chetwynd', 'Aliquam.rutrum.lorem@eleifendCras.edu', 80198, 4438),
  (81, 'Lyle Carter', 43, 'Cornwall', 'a.mi@Uttincidunt.ca', 742487, 1443),
  (82, 'Finn Alston', 27, 'Helkijn', 'dignissim@turpisegestas.com', 319985, 9892),
  (83, 'Caesar Dunlap', 37, 'Neu-Isenburg', 'a.malesuada@turpisnecmauris.com', 320218, 6949),
  (84, 'Barry Norris', 47, 'St. Asaph', 'parturient.montes.nascetur@semperrutrumFusce.ca', 782647, 9052),
  (85, 'Igor Kemp', 31, 'Petit-Hallet', 'nibh@eudui.net', 900643, 5830),
  (86, 'Julian Suarez', 42, 'Cabras', 'ipsum.ac.mi@magnaatortor.org', 226105, 9328),
  (87, 'Duncan Kirkland', 23, 'Townsville', 'Proin@commodo.net', 498229, 1407),
  (88, 'Blake Barlow', 33, 'Ipswich', 'amet.orci@semmagnanec.com', 420414, 3145),
  (89, 'Jin Meyer', 38, 'Inuvik', 'felis.ullamcorper.viverra@gravidamauris.org', 643413, 607),
  (90, 'Seth Davenport', 19, 'Limal', 'diam@Cumsociis.net', 628722, 1868),
  (91, 'Jamal Avila', 37, 'Maple Creek', 'euismod.urna@erosnectellus.org', 743693, 9735),
  (92, 'Keefe Buckley', 31, 'Stoke-on-Trent', 'erat@ultricessit.org', 81022, 7054),
  (93, 'Mannix Mclaughlin', 29, 'Bottidda', 'a.nunc@eu.co.uk', 767527, 515),
  (94, 'Curran Barker', 15, 'Silius', 'semper@vulputate.net', 835150, 4989),
  (95, 'Leroy Morales', 21, 'Pont-Saint-Martin', 'non@vitaeposuereat.com', 311662, 3260),
  (96, 'Buckminster Gordon', 45, 'Aklavik', 'metus@ametconsectetueradipiscing.co.uk', 609828, 5932),
  (97, 'Aidan Graves', 39, 'Broxburn', 'tincidunt.congue.turpis@necmalesuada.edu', 591328, 9564),
  (98, 'Price Roberts', 35, 'Castletown', 'mauris.aliquam.eu@justo.com', 38526, 498),
  (99, 'Darius Shaffer', 23, 'La Spezia', 'Quisque.tincidunt.pede@interdumligula.com', 722881, 9987),
  (100, 'Holmes Chen', 35, 'Guardia Sanframondi', 'semper@etmagnaPraesent.co.uk', 215672, 6695);


  /* Question data */

INSERT INTO question (qs_id, qs_user_id, qs_name, qs_votes, qs_content, qs_views)
VALUES

  (1, 78,
   'eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id',
   20,
   'mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum',
   82),
  (2, 47,
   'facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes,',
   87,
   'arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque',
   177),
  (3, 61, 'dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo.', 29,
   'justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc',
   2540),
  (4, 24,
   'sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie',
   10,
   'elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus',
   1876),
  (5, 36,
   'Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede,',
   8,
   'posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris',
   938),
  (6, 46,
   'purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est',
   36,
   'nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh',
   151),
  (7, 73,
   'dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam',
   13,
   'massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus',
   1016),
  (8, 71,
   'dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem',
   59,
   'metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis',
   1253),
  (9, 35, 'arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc', 94,
   'Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci',
   2231),
  (10, 8, 'tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas', 64,
   'ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor',
   2393);


  /* Comment data */

INSERT INTO comment (cm_id, cm_user_id, cm_question_id, cm_content)
VALUES
  (1, 63, 9,
   'Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus'),
(2, 100, 10, 'Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada'),
(3, 37, 7, 'vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris'),
(4, 84, 10, 'ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra.'),
(5, 43, 7, 'arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum,'),
(6, 93, 2, 'amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis'),
(7, 38, 4, 'eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus.'),
(8, 28, 9, 'tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus.'),
(9, 1, 3, 'adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus.'),
(10, 99, 3, 'imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede.'),
(11, 93, 9, 'libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et'),
(12, 1, 9, 'eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus'),
(13, 19, 9, 'nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis'),
(14, 17, 4, 'eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque'),
(15, 11, 3, 'nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut'),
(16, 72, 2, 'in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa.'),
(17, 95, 8, 'mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget'),
(18, 33, 1, 'adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor'),
(19, 77, 3, 'orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare'),
(20, 9, 5, 'lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut,'),
(21, 10, 4, 'sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum'),
(22, 94, 6, 'magna tellus faucibus leo, in lobortis tellus justo sit amet nulla.'),
(23, 69, 10, 'interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce'),
(24, 78, 7, 'ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem,'),
(25, 40, 6, 'lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at'),
(26, 92, 8, 'ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula'),
(27, 32, 2, 'vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis'),
(28, 39, 3, 'ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem.'),
(29, 66, 2, 'lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum.'),
(30, 67, 10, 'morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer'),
(31, 32, 8, 'Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat'),
(32, 16, 9, 'gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi,'),
(33, 9, 4, 'vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor,'),
(34, 51, 4, 'ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus.'),
(35, 98, 10, 'risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend'),
(36, 76, 8, 'pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis.'),
(37, 72, 5, 'vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae'),
(38, 66, 8, 'natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec'),
(39, 26, 9, 'non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in,'),
(40, 82, 8, 'sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue'),
(41, 87, 7, 'dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit'),
(42, 42, 4, 'montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean'),
(43, 45, 5, 'Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac'),
(44, 76, 9, 'gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue'),
(45, 14, 8, 'posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu'),
(46, 32, 8, 'blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec'),
(47, 55, 10, 'lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse'),
(48, 25, 6, 'sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu.'),
(49, 73, 5, 'Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla,'),
(50, 25, 5, 'ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam'),
(51, 17, 7, 'tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices'),
(52, 11, 4, 'a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque'),
(53, 91, 3, 'in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu'),
(54, 55, 3, 'metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut'),
(55, 4, 8, 'quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut,'),
(56, 77, 1, 'eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam'),
(57, 1, 9, 'mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at'),
(58, 63, 7, 'arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit'),
(59, 78, 8, 'Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim.'),
(60, 52, 9, 'lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing'),
(61, 17, 2, 'quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam'),
(62, 96, 3, 'nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis.'),
(63, 25, 1, 'eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et'),
(64, 61, 7, 'aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem'),
(65, 78, 9, 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel'),
(66, 17, 8, 'a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam'),
(67, 70, 8, 'odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec'),
(68, 47, 7, 'turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna'),
(69, 15, 6, 'luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id'),
(70, 96, 6, 'scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus.'),
(71, 67, 6, 'volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus'),
(72, 7, 8, 'in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia'),
(73, 79, 1, 'suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus'),
(74, 24, 5, 'fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam'),
(75, 20, 9, 'faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna.'),
(76, 86, 3, 'egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin'),
(77, 40, 9, 'Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut'),
(78, 32, 7, 'eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus.'),
(79, 98, 8, 'ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit.'),
(80, 85, 2, 'magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper'),
(81, 55, 3, 'mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus'),
(82, 45, 10, 'feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada'),
(83, 23, 3, 'sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta'),
(84, 72, 5, 'dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et'),
(85, 9, 8, 'malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque'),
(86, 7, 5, 'mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet'),
(87, 6, 8, 'eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis'),
(88, 75, 3, 'nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci.'),
(89, 99, 2, 'enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec'),
(90, 75, 7, 'vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra.'),
(91, 99, 8, 'ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis'),
  (92, 38, 7, 'augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada'),
  (93, 49, 2,
   'nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat.'),
  (94, 19, 8,
   'mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque.'),
  (95, 67, 1,
   'fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus,'),
  (96, 70, 6,
   'Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur'),
  (97, 58, 4,
   'mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec,'),
  (98, 11, 10,
   'ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus'),
  (99, 27, 3,
   'elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh'),
  (100, 17, 5,
   'tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy');