/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnswerRecord extends org.jooq.impl.UpdatableRecordImpl<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Byte> {

	private static final long serialVersionUID = -554309880;

	/**
	 * Setter for <code>adviceexchange.answer.asw_id</code>.
	 */
	public void setAswId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>adviceexchange.answer.asw_id</code>.
	 */
	public java.lang.Integer getAswId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>adviceexchange.answer.asw_question_id</code>.
	 */
	public void setAswQuestionId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>adviceexchange.answer.asw_question_id</code>.
	 */
	public java.lang.Integer getAswQuestionId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>adviceexchange.answer.asw_votes</code>.
	 */
	public void setAswVotes(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>adviceexchange.answer.asw_votes</code>.
	 */
	public java.lang.Integer getAswVotes() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>adviceexchange.answer.asw_accepted</code>.
	 */
	public void setAswAccepted(java.lang.Byte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>adviceexchange.answer.asw_accepted</code>.
	 */
	public java.lang.Byte getAswAccepted() {
		return (java.lang.Byte) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Byte> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.Answer.ANSWER.ASW_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.Answer.ANSWER.ASW_QUESTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.Answer.ANSWER.ASW_VOTES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field4() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.Answer.ANSWER.ASW_ACCEPTED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getAswId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getAswQuestionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getAswVotes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value4() {
		return getAswAccepted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value1(java.lang.Integer value) {
		setAswId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value2(java.lang.Integer value) {
		setAswQuestionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value3(java.lang.Integer value) {
		setAswVotes(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value4(java.lang.Byte value) {
		setAswAccepted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Byte value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AnswerRecord
	 */
	public AnswerRecord() {
		super(com.dozortsev.adviceexchange.domain.jooq.tables.Answer.ANSWER);
	}

	/**
	 * Create a detached, initialised AnswerRecord
	 */
	public AnswerRecord(java.lang.Integer aswId, java.lang.Integer aswQuestionId, java.lang.Integer aswVotes, java.lang.Byte aswAccepted) {
		super(com.dozortsev.adviceexchange.domain.jooq.tables.Answer.ANSWER);

		setValue(0, aswId);
		setValue(1, aswQuestionId);
		setValue(2, aswVotes);
		setValue(3, aswAccepted);
	}
}
