/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnswerRecord extends org.jooq.impl.UpdatableRecordImpl<com.dozortsev.adviceexchange.domain.jooq.tables.records.AnswerRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.Byte> {

	private static final long serialVersionUID = 2123402281;

	/**
	 * Setter for <code>adviceexchange.answer.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>adviceexchange.answer.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>adviceexchange.answer.qt_id</code>.
	 */
	public void setQtId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>adviceexchange.answer.qt_id</code>.
	 */
	public java.lang.Integer getQtId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>adviceexchange.answer.accepted</code>.
	 */
	public void setAccepted(java.lang.Byte value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>adviceexchange.answer.accepted</code>.
	 */
	public java.lang.Byte getAccepted() {
		return (java.lang.Byte) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Byte> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER.QT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field3() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER.ACCEPTED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getQtId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value3() {
		return getAccepted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value2(java.lang.Integer value) {
		setQtId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value3(java.lang.Byte value) {
		setAccepted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Byte value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AnswerRecord
	 */
	public AnswerRecord() {
		super(com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER);
	}

	/**
	 * Create a detached, initialised AnswerRecord
	 */
	public AnswerRecord(java.lang.Integer id, java.lang.Integer qtId, java.lang.Byte accepted) {
		super(com.dozortsev.adviceexchange.domain.jooq.tables.TAnswer.ANSWER);

		setValue(0, id);
		setValue(1, qtId);
		setValue(2, accepted);
	}
}
