/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BadgeRecord extends org.jooq.impl.UpdatableRecordImpl<com.dozortsev.adviceexchange.domain.jooq.tables.records.BadgeRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -326451675;

	/**
	 * Setter for <code>adviceexchange.badge.bdg_id</code>.
	 */
	public void setBdgId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>adviceexchange.badge.bdg_id</code>.
	 */
	public java.lang.Integer getBdgId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>adviceexchange.badge.bdg_name</code>.
	 */
	public void setBdgName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>adviceexchange.badge.bdg_name</code>.
	 */
	public java.lang.String getBdgName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>adviceexchange.badge.bdg_desc</code>.
	 */
	public void setBdgDesc(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>adviceexchange.badge.bdg_desc</code>.
	 */
	public java.lang.String getBdgDesc() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.Badge.BADGE.BDG_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.Badge.BADGE.BDG_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.Badge.BADGE.BDG_DESC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getBdgId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getBdgName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getBdgDesc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BadgeRecord value1(java.lang.Integer value) {
		setBdgId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BadgeRecord value2(java.lang.String value) {
		setBdgName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BadgeRecord value3(java.lang.String value) {
		setBdgDesc(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BadgeRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BadgeRecord
	 */
	public BadgeRecord() {
		super(com.dozortsev.adviceexchange.domain.jooq.tables.Badge.BADGE);
	}

	/**
	 * Create a detached, initialised BadgeRecord
	 */
	public BadgeRecord(java.lang.Integer bdgId, java.lang.String bdgName, java.lang.String bdgDesc) {
		super(com.dozortsev.adviceexchange.domain.jooq.tables.Badge.BADGE);

		setValue(0, bdgId);
		setValue(1, bdgName);
		setValue(2, bdgDesc);
	}
}
