/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserActivityRecord extends org.jooq.impl.UpdatableRecordImpl<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> implements org.jooq.Record6<java.lang.Integer, com.dozortsev.adviceexchange.domain.jooq.enums.UserActivityType, java.lang.Integer, java.lang.String, java.lang.Byte, java.sql.Timestamp> {

	private static final long serialVersionUID = 1036763447;

	/**
	 * Setter for <code>adviceexchange.user_activity.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>adviceexchange.user_activity.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>adviceexchange.user_activity.type</code>.
	 */
	public void setType(com.dozortsev.adviceexchange.domain.jooq.enums.UserActivityType value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>adviceexchange.user_activity.type</code>.
	 */
	public com.dozortsev.adviceexchange.domain.jooq.enums.UserActivityType getType() {
		return (com.dozortsev.adviceexchange.domain.jooq.enums.UserActivityType) getValue(1);
	}

	/**
	 * Setter for <code>adviceexchange.user_activity.user_id</code>.
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>adviceexchange.user_activity.user_id</code>.
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>adviceexchange.user_activity.content</code>.
	 */
	public void setContent(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>adviceexchange.user_activity.content</code>.
	 */
	public java.lang.String getContent() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>adviceexchange.user_activity.active</code>.
	 */
	public void setActive(java.lang.Byte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>adviceexchange.user_activity.active</code>.
	 */
	public java.lang.Byte getActive() {
		return (java.lang.Byte) getValue(4);
	}

	/**
	 * Setter for <code>adviceexchange.user_activity.created</code>.
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>adviceexchange.user_activity.created</code>.
	 */
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, com.dozortsev.adviceexchange.domain.jooq.enums.UserActivityType, java.lang.Integer, java.lang.String, java.lang.Byte, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, com.dozortsev.adviceexchange.domain.jooq.enums.UserActivityType, java.lang.Integer, java.lang.String, java.lang.Byte, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.dozortsev.adviceexchange.domain.jooq.enums.UserActivityType> field2() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field5() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY.ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.dozortsev.adviceexchange.domain.jooq.enums.UserActivityType value2() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value5() {
		return getActive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserActivityRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserActivityRecord value2(com.dozortsev.adviceexchange.domain.jooq.enums.UserActivityType value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserActivityRecord value3(java.lang.Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserActivityRecord value4(java.lang.String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserActivityRecord value5(java.lang.Byte value) {
		setActive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserActivityRecord value6(java.sql.Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserActivityRecord values(java.lang.Integer value1, com.dozortsev.adviceexchange.domain.jooq.enums.UserActivityType value2, java.lang.Integer value3, java.lang.String value4, java.lang.Byte value5, java.sql.Timestamp value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserActivityRecord
	 */
	public UserActivityRecord() {
		super(com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY);
	}

	/**
	 * Create a detached, initialised UserActivityRecord
	 */
	public UserActivityRecord(java.lang.Integer id, com.dozortsev.adviceexchange.domain.jooq.enums.UserActivityType type, java.lang.Integer userId, java.lang.String content, java.lang.Byte active, java.sql.Timestamp created) {
		super(com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY);

		setValue(0, id);
		setValue(1, type);
		setValue(2, userId);
		setValue(3, content);
		setValue(4, active);
		setValue(5, created);
	}
}
