/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserActivityRecord extends org.jooq.impl.UpdatableRecordImpl<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserActivityRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Byte, java.sql.Timestamp> {

	private static final long serialVersionUID = 943271737;

	/**
	 * Setter for <code>adviceexchange.user_activity.ua_id</code>.
	 */
	public void setUaId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>adviceexchange.user_activity.ua_id</code>.
	 */
	public java.lang.Integer getUaId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>adviceexchange.user_activity.ua_type</code>.
	 */
	public void setUaType(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>adviceexchange.user_activity.ua_type</code>.
	 */
	public java.lang.String getUaType() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>adviceexchange.user_activity.ua_user_id</code>.
	 */
	public void setUaUserId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>adviceexchange.user_activity.ua_user_id</code>.
	 */
	public java.lang.Integer getUaUserId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>adviceexchange.user_activity.ua_content</code>.
	 */
	public void setUaContent(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>adviceexchange.user_activity.ua_content</code>.
	 */
	public java.lang.String getUaContent() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>adviceexchange.user_activity.ua_active</code>.
	 */
	public void setUaActive(java.lang.Byte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>adviceexchange.user_activity.ua_active</code>.
	 */
	public java.lang.Byte getUaActive() {
		return (java.lang.Byte) getValue(4);
	}

	/**
	 * Setter for <code>adviceexchange.user_activity.ua_created</code>.
	 */
	public void setUaCreated(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>adviceexchange.user_activity.ua_created</code>.
	 */
	public java.sql.Timestamp getUaCreated() {
		return (java.sql.Timestamp) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Byte, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Byte, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY.UA_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY.UA_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY.UA_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY.UA_CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field5() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY.UA_ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY.UA_CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUaId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUaType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getUaUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getUaContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value5() {
		return getUaActive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getUaCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserActivityRecord value1(java.lang.Integer value) {
		setUaId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserActivityRecord value2(java.lang.String value) {
		setUaType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserActivityRecord value3(java.lang.Integer value) {
		setUaUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserActivityRecord value4(java.lang.String value) {
		setUaContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserActivityRecord value5(java.lang.Byte value) {
		setUaActive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserActivityRecord value6(java.sql.Timestamp value) {
		setUaCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserActivityRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3, java.lang.String value4, java.lang.Byte value5, java.sql.Timestamp value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserActivityRecord
	 */
	public UserActivityRecord() {
		super(com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY);
	}

	/**
	 * Create a detached, initialised UserActivityRecord
	 */
	public UserActivityRecord(java.lang.Integer uaId, java.lang.String uaType, java.lang.Integer uaUserId, java.lang.String uaContent, java.lang.Byte uaActive, java.sql.Timestamp uaCreated) {
		super(com.dozortsev.adviceexchange.domain.jooq.tables.UserActivity.USER_ACTIVITY);

		setValue(0, uaId);
		setValue(1, uaType);
		setValue(2, uaUserId);
		setValue(3, uaContent);
		setValue(4, uaActive);
		setValue(5, uaCreated);
	}
}
