/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends org.jooq.impl.UpdatableRecordImpl<com.dozortsev.adviceexchange.domain.jooq.tables.records.UserRecord> implements org.jooq.Record11<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Integer> {

	private static final long serialVersionUID = -1070766690;

	/**
	 * Setter for <code>adviceexchange.user.user_id</code>.
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>adviceexchange.user.user_id</code>.
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>adviceexchange.user.user_name</code>.
	 */
	public void setUserName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>adviceexchange.user.user_name</code>.
	 */
	public java.lang.String getUserName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>adviceexchange.user.user_age</code>.
	 */
	public void setUserAge(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>adviceexchange.user.user_age</code>.
	 */
	public java.lang.Integer getUserAge() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>adviceexchange.user.user_about_me</code>.
	 */
	public void setUserAboutMe(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>adviceexchange.user.user_about_me</code>.
	 */
	public java.lang.String getUserAboutMe() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>adviceexchange.user.user_joined</code>.
	 */
	public void setUserJoined(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>adviceexchange.user.user_joined</code>.
	 */
	public java.sql.Timestamp getUserJoined() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>adviceexchange.user.user_location</code>.
	 */
	public void setUserLocation(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>adviceexchange.user.user_location</code>.
	 */
	public java.lang.String getUserLocation() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>adviceexchange.user.user_site</code>.
	 */
	public void setUserSite(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>adviceexchange.user.user_site</code>.
	 */
	public java.lang.String getUserSite() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>adviceexchange.user.user_email</code>.
	 */
	public void setUserEmail(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>adviceexchange.user.user_email</code>.
	 */
	public java.lang.String getUserEmail() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>adviceexchange.user.user_password</code>.
	 */
	public void setUserPassword(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>adviceexchange.user.user_password</code>.
	 */
	public java.lang.String getUserPassword() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>adviceexchange.user.user_enabled</code>.
	 */
	public void setUserEnabled(java.lang.Byte value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>adviceexchange.user.user_enabled</code>.
	 */
	public java.lang.Byte getUserEnabled() {
		return (java.lang.Byte) getValue(9);
	}

	/**
	 * Setter for <code>adviceexchange.user.user_reputation</code>.
	 */
	public void setUserReputation(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>adviceexchange.user.user_reputation</code>.
	 */
	public java.lang.Integer getUserReputation() {
		return (java.lang.Integer) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Integer> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.User.USER.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.User.USER.USER_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.User.USER.USER_AGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.User.USER.USER_ABOUT_ME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.User.USER.USER_JOINED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.User.USER.USER_LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.User.USER.USER_SITE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.User.USER.USER_EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.User.USER.USER_PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field10() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.User.USER.USER_ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return com.dozortsev.adviceexchange.domain.jooq.tables.User.USER.USER_REPUTATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUserName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getUserAge();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getUserAboutMe();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getUserJoined();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getUserLocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getUserSite();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getUserEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getUserPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value10() {
		return getUserEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getUserReputation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value1(java.lang.Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value2(java.lang.String value) {
		setUserName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value3(java.lang.Integer value) {
		setUserAge(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value4(java.lang.String value) {
		setUserAboutMe(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value5(java.sql.Timestamp value) {
		setUserJoined(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value6(java.lang.String value) {
		setUserLocation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value7(java.lang.String value) {
		setUserSite(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value8(java.lang.String value) {
		setUserEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value9(java.lang.String value) {
		setUserPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value10(java.lang.Byte value) {
		setUserEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value11(java.lang.Integer value) {
		setUserReputation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3, java.lang.String value4, java.sql.Timestamp value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.Byte value10, java.lang.Integer value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserRecord
	 */
	public UserRecord() {
		super(com.dozortsev.adviceexchange.domain.jooq.tables.User.USER);
	}

	/**
	 * Create a detached, initialised UserRecord
	 */
	public UserRecord(java.lang.Integer userId, java.lang.String userName, java.lang.Integer userAge, java.lang.String userAboutMe, java.sql.Timestamp userJoined, java.lang.String userLocation, java.lang.String userSite, java.lang.String userEmail, java.lang.String userPassword, java.lang.Byte userEnabled, java.lang.Integer userReputation) {
		super(com.dozortsev.adviceexchange.domain.jooq.tables.User.USER);

		setValue(0, userId);
		setValue(1, userName);
		setValue(2, userAge);
		setValue(3, userAboutMe);
		setValue(4, userJoined);
		setValue(5, userLocation);
		setValue(6, userSite);
		setValue(7, userEmail);
		setValue(8, userPassword);
		setValue(9, userEnabled);
		setValue(10, userReputation);
	}
}
