/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Answer extends UserActivity implements java.io.Serializable {

	private static final long serialVersionUID = -20771368;

	private java.lang.Integer id;
	private java.lang.Integer qtId;
	private java.lang.Byte    accepted;

	public Answer() {}

	public Answer(
		java.lang.Integer id,
		java.lang.Integer qtId,
		java.lang.Byte    accepted
	) {
		this.id = id;
		this.qtId = qtId;
		this.accepted = accepted;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getQtId() {
		return this.qtId;
	}

	public void setQtId(java.lang.Integer qtId) {
		this.qtId = qtId;
	}

	public java.lang.Byte getAccepted() {
		return this.accepted;
	}

	public void setAccepted(java.lang.Byte accepted) {
		this.accepted = accepted;
	}
}
