/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comment extends UserActivity implements java.io.Serializable {

	private static final long serialVersionUID = 834031589;

	private java.lang.Integer id;
	private java.lang.Integer qtId;

	public Comment() {}

	public Comment(
		java.lang.Integer id,
		java.lang.Integer qtId
	) {
		this.id = id;
		this.qtId = qtId;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getQtId() {
		return this.qtId;
	}

	public void setQtId(java.lang.Integer qtId) {
		this.qtId = qtId;
	}
}
