/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuestionTag extends java.lang.Object implements java.io.Serializable {

	private static final long serialVersionUID = 2086985575;

	private java.lang.Integer qtId;
	private java.lang.Integer tagId;

	public QuestionTag() {}

	public QuestionTag(
		java.lang.Integer qtId,
		java.lang.Integer tagId
	) {
		this.qtId = qtId;
		this.tagId = tagId;
	}

	public java.lang.Integer getQtId() {
		return this.qtId;
	}

	public void setQtId(java.lang.Integer qtId) {
		this.qtId = qtId;
	}

	public java.lang.Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(java.lang.Integer tagId) {
		this.tagId = tagId;
	}
}
