/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tag extends java.lang.Object implements java.io.Serializable {

	private static final long serialVersionUID = 1964876905;

	private java.lang.Integer id;
	private java.lang.String  name;
	private java.lang.String  desc;

	public Tag() {}

	public Tag(
		java.lang.Integer id,
		java.lang.String  name,
		java.lang.String  desc
	) {
		this.id = id;
		this.name = name;
		this.desc = desc;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDesc() {
		return this.desc;
	}

	public void setDesc(java.lang.String desc) {
		this.desc = desc;
	}
}
