/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserActivity extends java.lang.Object implements java.io.Serializable {

	private static final long serialVersionUID = 1778509159;

	private java.lang.Integer                                               id;
	private com.dozortsev.adviceexchange.domain.jooq.enums.UserActivityType type;
	private java.lang.Integer                                               userId;
	private java.lang.String                                                content;
	private java.lang.Byte                                                  active;
	private java.sql.Timestamp                                              created;
	private java.lang.Integer                                               totalscore;

	public UserActivity() {}

	public UserActivity(
		java.lang.Integer                                               id,
		com.dozortsev.adviceexchange.domain.jooq.enums.UserActivityType type,
		java.lang.Integer                                               userId,
		java.lang.String                                                content,
		java.lang.Byte                                                  active,
		java.sql.Timestamp                                              created,
		java.lang.Integer                                               totalscore
	) {
		this.id = id;
		this.type = type;
		this.userId = userId;
		this.content = content;
		this.active = active;
		this.created = created;
		this.totalscore = totalscore;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public com.dozortsev.adviceexchange.domain.jooq.enums.UserActivityType getType() {
		return this.type;
	}

	public void setType(com.dozortsev.adviceexchange.domain.jooq.enums.UserActivityType type) {
		this.type = type;
	}

	public java.lang.Integer getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.Integer userId) {
		this.userId = userId;
	}

	public java.lang.String getContent() {
		return this.content;
	}

	public void setContent(java.lang.String content) {
		this.content = content;
	}

	public java.lang.Byte getActive() {
		return this.active;
	}

	public void setActive(java.lang.Byte active) {
		this.active = active;
	}

	public java.sql.Timestamp getCreated() {
		return this.created;
	}

	public void setCreated(java.sql.Timestamp created) {
		this.created = created;
	}

	public java.lang.Integer getTotalscore() {
		return this.totalscore;
	}

	public void setTotalscore(java.lang.Integer totalscore) {
		this.totalscore = totalscore;
	}
}
