/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends java.lang.Object implements java.io.Serializable {

	private static final long serialVersionUID = 1500391658;

	private java.lang.Integer  id;
	private java.lang.String   name;
	private java.lang.Integer  age;
	private java.lang.String   aboutMe;
	private java.sql.Timestamp joined;
	private java.lang.String   location;
	private java.lang.String   site;
	private java.lang.String   email;
	private java.lang.String   password;
	private java.lang.Byte     enabled;
	private java.lang.Integer  reputation;

	public User() {}

	public User(
		java.lang.Integer  id,
		java.lang.String   name,
		java.lang.Integer  age,
		java.lang.String   aboutMe,
		java.sql.Timestamp joined,
		java.lang.String   location,
		java.lang.String   site,
		java.lang.String   email,
		java.lang.String   password,
		java.lang.Byte     enabled,
		java.lang.Integer  reputation
	) {
		this.id = id;
		this.name = name;
		this.age = age;
		this.aboutMe = aboutMe;
		this.joined = joined;
		this.location = location;
		this.site = site;
		this.email = email;
		this.password = password;
		this.enabled = enabled;
		this.reputation = reputation;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getAboutMe() {
		return this.aboutMe;
	}

	public void setAboutMe(java.lang.String aboutMe) {
		this.aboutMe = aboutMe;
	}

	public java.sql.Timestamp getJoined() {
		return this.joined;
	}

	public void setJoined(java.sql.Timestamp joined) {
		this.joined = joined;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public java.lang.String getSite() {
		return this.site;
	}

	public void setSite(java.lang.String site) {
		this.site = site;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getPassword() {
		return this.password;
	}

	public void setPassword(java.lang.String password) {
		this.password = password;
	}

	public java.lang.Byte getEnabled() {
		return this.enabled;
	}

	public void setEnabled(java.lang.Byte enabled) {
		this.enabled = enabled;
	}

	public java.lang.Integer getReputation() {
		return this.reputation;
	}

	public void setReputation(java.lang.Integer reputation) {
		this.reputation = reputation;
	}
}
