/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserBadge extends java.lang.Object implements java.io.Serializable {

	private static final long serialVersionUID = 1576750701;

	private java.lang.Integer badgeId;
	private java.lang.Integer userId;

	public UserBadge() {}

	public UserBadge(
		java.lang.Integer badgeId,
		java.lang.Integer userId
	) {
		this.badgeId = badgeId;
		this.userId = userId;
	}

	public java.lang.Integer getBadgeId() {
		return this.badgeId;
	}

	public void setBadgeId(java.lang.Integer badgeId) {
		this.badgeId = badgeId;
	}

	public java.lang.Integer getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.Integer userId) {
		this.userId = userId;
	}
}
