/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vote extends java.lang.Object implements java.io.Serializable {

	private static final long serialVersionUID = -1122754211;

	private java.lang.Integer  id;
	private java.lang.Integer  userId;
	private java.lang.Integer  activityId;
	private java.lang.Integer  score;
	private java.sql.Timestamp created;

	public Vote() {}

	public Vote(
		java.lang.Integer  id,
		java.lang.Integer  userId,
		java.lang.Integer  activityId,
		java.lang.Integer  score,
		java.sql.Timestamp created
	) {
		this.id = id;
		this.userId = userId;
		this.activityId = activityId;
		this.score = score;
		this.created = created;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.Integer userId) {
		this.userId = userId;
	}

	public java.lang.Integer getActivityId() {
		return this.activityId;
	}

	public void setActivityId(java.lang.Integer activityId) {
		this.activityId = activityId;
	}

	public java.lang.Integer getScore() {
		return this.score;
	}

	public void setScore(java.lang.Integer score) {
		this.score = score;
	}

	public java.sql.Timestamp getCreated() {
		return this.created;
	}

	public void setCreated(java.sql.Timestamp created) {
		this.created = created;
	}
}
