/**
 * This class is generated by jOOQ
 */
package com.dozortsev.adviceexchange.domain.jooq.enums;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum UserActivityType implements org.jooq.EnumType {

	ANSWER("ANSWER"),

	QUESTION("QUESTION"),

	COMMENT("COMMENT");

	private final java.lang.String literal;

	private UserActivityType(java.lang.String literal) {
		this.literal = literal;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Schema getSchema() {
		return null;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String getName() {
		return "user_activity_type";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String getLiteral() {
		return literal;
	}
}
