
/* Badge data */

INSERT INTO badge (bdg_id, bdg_name, bdg_desc) VALUES

  (1, 'Admin', 'One who oversees discussions on an Internet forum'),
  (2, 'User', 'A person using a generic system');

/* User data */

INSERT INTO user (user_id, user_name, user_age, user_location, user_email, user_password, user_reputation) VALUES

  (1, 'Ross Oconnor', 24, 'Ulloa Barrial', 'sed.dui.Fusce@torquentperconubia.net', 341442, 9471),
  (2, 'Stone Davis', 20, 'Renlies', 'Mauris.vestibulum@convallis.org', 296400, 3795),
  (3, 'Henry Mcmahon', 41, 'Valera Fratta', 'vitae.aliquet.nec@inconsequat.edu', 779347, 6946),
  (4, 'Honorato Manning', 17, 'Arendonk', 'pede.Suspendisse.dui@malesuada.org', 424781, 1185),
  (5, 'Joshua Foley', 28, 'Penna San Giovanni', 'enim.Sed.nulla@magnis.ca', 982360, 3001),
  (6, 'Merrill Cotton', 38, 'St. Davids', 'enim.nisl@pulvinararcuet.org', 576987, 4259),
  (7, 'Kelly Singleton', 46, 'Mannheim', 'aliquet.vel@temporest.co.uk', 300125, 9370),
  (8, 'Herman Cabrera', 49, 'Landenne', 'consectetuer.adipiscing.elit@liberoMorbiaccumsan.ca', 225793, 8475),
  (9, 'Gannon Patterson', 18, 'Albi', 'risus@accumsan.com', 634194, 5473),
  (10, 'Finn Burris', 37, 'Sint-Stevens-Woluwe', 'adipiscing.Mauris@Fuscealiquetmagna.net', 159980, 5616),
  (11, 'Brett Ferrell', 36, 'Watford', 'ut.dolor@etmagnisdis.ca', 553748, 2892),
  (12, 'Sawyer Lynn', 44, 'Cropalati', 'mauris.erat.eget@Nunc.edu', 94548, 5272),
  (13, 'Reuben Washington', 41, 'Hattiesburg', 'nunc.interdum@et.net', 504951, 9286),
  (14, 'Deacon Craft', 48, 'Sint-Pieters-Kapelle', 'velit.Sed@risusvariusorci.co.uk', 361091, 5734),
  (15, 'Drew Mejia', 16, 'Le Havre', 'rhoncus.Donec.est@enimCurabitur.org', 737307, 7579),
  (16, 'Levi Swanson', 35, 'Warspite', 'semper.Nam.tempor@penatibus.ca', 925535, 3059),
  (17, 'Brett Kaufman', 42, 'Ruette', 'Nulla.semper.tellus@et.edu', 399319, 1731),
  (18, 'Rogan Dennis', 48, 'Caloundra', 'convallis.convallis@congueaaliquet.co.uk', 715399, 1191),
  (19, 'Walter Castro', 35, 'Milwaukee', 'Nunc.sed.orci@velit.edu', 104172, 8551),
  (20, 'Maxwell Haley', 27, 'Lamontzï¿½e', 'malesuada.vel@iaculisenimsit.edu', 488557, 9892),
  (21, 'Kevin Strong', 48, 'Caplan', 'lobortis.Class@sit.org', 396577, 3816),
  (22, 'Oren Hopper', 16, 'Fuenlabrada', 'tellus@mollisnec.edu', 490178, 6230),
  (23, 'Fritz Ballard', 19, 'Qu?bec City', 'consectetuer.mauris@ultriciessem.edu', 41803, 7871),
  (24, 'Aristotle Castillo', 19, 'Naninne', 'purus@bibendum.edu', 815124, 3652),
  (25, 'Charles Foreman', 29, 'Hattiesburg', 'diam.luctus.lobortis@nonummyultricies.ca', 766777, 509),
  (26, 'Hunter Houston', 33, 'Tracadie-Shelia', 'magnis.dis@velarcueu.co.uk', 577094, 2292),
  (27, 'Rahim Ayala', 44, 'Wieze', 'dui@liberomauris.edu', 406370, 3923),
  (28, 'Phillip Snyder', 36, 'Kaaskerke', 'accumsan@adipiscingelitEtiam.edu', 769786, 5405),
  (29, 'Coby Banks', 42, 'Talence', 'Cras.convallis@diamSeddiam.com', 963775, 5685),
  (30, 'Timon Rhodes', 46, 'Kruibeke', 'scelerisque.lorem@ultricies.edu', 640118, 8009),
  (31, 'Deacon Mclaughlin', 39, 'Leamington', 'pede.sagittis.augue@sem.org', 702999, 5491),
  (32, 'Rafael Stanley', 34, 'Weston-super-Mare', 'quis.tristique.ac@euduiCum.net', 146414, 2796),
  (33, 'Mason Hodges', 47, 'Lawton', 'Morbi@lacus.co.uk', 550428, 9346),
  (34, 'Fulton Rosario', 27, 'Eisden', 'lectus.ante@enim.co.uk', 685561, 6084),
  (35, 'Kamal Maxwell', 30, 'Hospitalet de Llobregat', 'Vestibulum@Duisa.net', 121871, 3526),
  (36, 'Luke Kirkland', 23, 'Andalo', 'neque.vitae@Nulla.org', 946911, 9501),
  (37, 'Solomon Reeves', 49, 'Kilwinning', 'aliquet.odio.Etiam@lobortisquam.org', 364177, 4939),
  (38, 'Tanek Lambert', 31, 'Saint-Marcel', 'vestibulum@augueeutellus.ca', 476209, 2296),
  (39, 'Patrick Buck', 27, 'Baltimore', 'facilisis.magna.tellus@ut.ca', 805328, 9965),
  (40, 'Drake Ochoa', 44, 'Hay River', 'bibendum@massanon.net', 510093, 3564),
  (41, 'Alfonso Chen', 50, 'Wondelgem', 'Curabitur@idblanditat.net', 987740, 1068),
  (42, 'Quinn Skinner', 20, 'Anderlecht', 'dictum@fermentummetus.co.uk', 327315, 2473),
  (43, 'Tyrone Mullen', 20, 'Wanaka', 'volutpat.Nulla.facilisis@fringilla.co.uk', 527740, 4297),
  (44, 'Isaiah Jensen', 33, 'Wellingborough', 'eu@enimnectempus.org', 749092, 8812),
  (45, 'Kennedy Trevino', 48, 'Leers-et-Fosteau', 'non@erategettincidunt.org', 251530, 7514),
  (46, 'Chaim Mcguire', 32, 'Sale', 'nisl.Maecenas.malesuada@Aliquam.edu', 235279, 9800),
  (47, 'Martin Price', 40, 'Lebach', 'et.nunc.Quisque@Phasellusdolorelit.net', 875540, 8614),
  (48, 'Tobias Key', 37, 'Bischofshofen', 'pellentesque.Sed@feugiat.co.uk', 976908, 5748),
  (49, 'Vernon Massey', 27, 'Gelsenkirchen', 'ipsum.dolor.sit@mollisInteger.net', 870561, 6137),
  (50, 'Gray Rosario', 41, 'Silverton', 'libero@inaliquetlobortis.ca', 119838, 4025),
  (51, 'Aaron Vasquez', 19, 'Hatfield', 'odio.Phasellus@lacus.edu', 809505, 3923),
  (52, 'Theodore Beach', 31, 'Orvault', 'mauris@pedeNuncsed.edu', 337314, 7437),
  (53, 'Tanner Mccullough', 25, 'Villa Cortese', 'et@Cras.co.uk', 854068, 8345),
  (54, 'Gray Sweeney', 15, 'Rebecq', 'erat.nonummy@Nullamlobortisquam.org', 187759, 2490),
  (55, 'Cameron Stevenson', 30, 'Rhisnes', 'ornare@semperduilectus.edu', 233514, 5592),
  (56, 'Lyle Patel', 48, 'Cirencester', 'Cras.interdum.Nunc@nullaIntegerurna.ca', 694740, 3988),
  (57, 'Adam Thompson', 24, 'Boechout', 'ipsum.primis@Proinsed.ca', 735265, 2347),
  (58, 'Arden Barry', 40, 'Vespolate', 'felis.orci.adipiscing@IntegermollisInteger.edu', 487273, 3632),
  (59, 'Gabriel Pate', 26, 'Dumfries', 'Duis.mi@a.edu', 405548, 4467),
  (60, 'Carlos Ford', 35, 'Picture Butte', 'lectus@ligulatortordictum.org', 925851, 9126),
  (61, 'Nolan Lane', 16, 'Castiglione a Casauria', 'aliquam@elitsedconsequat.co.uk', 683141, 2450),
  (62, 'Valentine Alvarez', 26, 'Krems an der Donau', 'nec.cursus@etmagnisdis.org', 30609, 5394),
  (63, 'Preston Mcclure', 46, 'Dunstable', 'orci@idrisusquis.com', 858888, 6660),
  (64, 'Wing Randolph', 45, 'Saint-RhÃ©my-en-Bosses', 'eu.eros.Nam@vitaealiquetnec.net', 153471, 7449),
  (65, 'Neil Berg', 44, 'College', 'ante@pede.com', 855939, 2661),
  (66, 'Reese Wilson', 37, 'Kitimat', 'erat.volutpat@imperdietnecleo.ca', 161592, 3319),
  (67, 'Kibo Barlow', 48, 'Kessenich', 'ac.ipsum.Phasellus@temporaugue.ca', 143825, 2122),
  (68, 'Arthur Atkinson', 48, 'Santa Maria a Monte', 'sit.amet@malesuadaaugueut.org', 459580, 6765),
  (69, 'Zachery Barron', 22, 'Verdun', 'nec.eleifend@vehicula.ca', 117098, 8221),
  (70, 'Oren Bender', 37, 'Liverpool', 'amet.luctus.vulputate@vehiculaaliquetlibero.org', 47034, 8776),
  (71, 'Steven Austin', 35, 'Amsterdam', 'eget.metus@diam.org', 248441, 2508),
  (72, 'James Randall', 20, 'Billings', 'luctus.vulputate@in.net', 847599, 2147),
  (73, 'Jeremy Turner', 33, 'Tranent', 'aliquet.vel@erosnonenim.co.uk', 374756, 8050),
  (74, 'Troy Little', 41, 'Steendorp', 'montes.nascetur.ridiculus@acarcu.edu', 410520, 4737),
  (75, 'Hamilton Franklin', 25, 'Toulouse', 'In@dolornonummyac.ca', 196385, 2215),
  (76, 'Isaiah Bowen', 39, 'Heusden', 'tellus.Aenean.egestas@magnisdisparturient.co.uk', 606721, 8810),
  (77, 'Laith Patton', 42, 'Spaniards Bay', 'nibh.Donec.est@facilisisloremtristique.org', 742473, 2668),
  (78, 'Jonas Meyers', 19, 'Medicine Hat', 'morbi.tristique@ultrices.ca', 380903, 1177),
  (79, 'Kenneth Joyner', 18, 'Tenby', 'Quisque.porttitor@perinceptos.net', 748594, 584),
  (80, 'Valentine Vang', 21, 'Chetwynd', 'Aliquam.rutrum.lorem@eleifendCras.edu', 80198, 4438),
  (81, 'Lyle Carter', 43, 'Cornwall', 'a.mi@Uttincidunt.ca', 742487, 1443),
  (82, 'Finn Alston', 27, 'Helkijn', 'dignissim@turpisegestas.com', 319985, 9892),
  (83, 'Caesar Dunlap', 37, 'Neu-Isenburg', 'a.malesuada@turpisnecmauris.com', 320218, 6949),
  (84, 'Barry Norris', 47, 'St. Asaph', 'parturient.montes.nascetur@semperrutrumFusce.ca', 782647, 9052),
  (85, 'Igor Kemp', 31, 'Petit-Hallet', 'nibh@eudui.net', 900643, 5830),
  (86, 'Julian Suarez', 42, 'Cabras', 'ipsum.ac.mi@magnaatortor.org', 226105, 9328),
  (87, 'Duncan Kirkland', 23, 'Townsville', 'Proin@commodo.net', 498229, 1407),
  (88, 'Blake Barlow', 33, 'Ipswich', 'amet.orci@semmagnanec.com', 420414, 3145),
  (89, 'Jin Meyer', 38, 'Inuvik', 'felis.ullamcorper.viverra@gravidamauris.org', 643413, 607),
  (90, 'Seth Davenport', 19, 'Limal', 'diam@Cumsociis.net', 628722, 1868),
  (91, 'Jamal Avila', 37, 'Maple Creek', 'euismod.urna@erosnectellus.org', 743693, 9735),
  (92, 'Keefe Buckley', 31, 'Stoke-on-Trent', 'erat@ultricessit.org', 81022, 7054),
  (93, 'Mannix Mclaughlin', 29, 'Bottidda', 'a.nunc@eu.co.uk', 767527, 515),
  (94, 'Curran Barker', 15, 'Silius', 'semper@vulputate.net', 835150, 4989),
  (95, 'Leroy Morales', 21, 'Pont-Saint-Martin', 'non@vitaeposuereat.com', 311662, 3260),
  (96, 'Buckminster Gordon', 45, 'Aklavik', 'metus@ametconsectetueradipiscing.co.uk', 609828, 5932),
  (97, 'Aidan Graves', 39, 'Broxburn', 'tincidunt.congue.turpis@necmalesuada.edu', 591328, 9564),
  (98, 'Price Roberts', 35, 'Castletown', 'mauris.aliquam.eu@justo.com', 38526, 498),
  (99, 'Darius Shaffer', 23, 'La Spezia', 'Quisque.tincidunt.pede@interdumligula.com', 722881, 9987),
  (100, 'Holmes Chen', 35, 'Guardia Sanframondi', 'semper@etmagnaPraesent.co.uk', 215672, 6695);


/* User & Badge data */

INSERT INTO user_badge (ub_badge_id, ub_user_id) VALUES

  (1, 90), (1, 5), (1, 79), (2, 80), (1, 38), (1, 51), (1, 84), (1, 8), (2, 56), (1, 59), (1, 28), (1, 100), (1, 70), (1, 19), (1, 66), (2, 16), (1, 63), (1, 65), (1, 12), (1, 75),
  (1, 21), (2, 3), (1, 8), (1, 3), (1, 88), (1, 63), (1, 21), (2, 79), (1, 28), (2, 44), (1, 79), (2, 6), (2, 100), (1, 99), (2, 48), (1, 57), (1, 2), (1, 31), (2, 97), (2, 60), (2, 85),
  (1, 81), (2, 74), (2, 1), (2, 68), (2, 30), (2, 41), (2, 80), (2, 42), (1, 39), (2, 61), (1, 97), (2, 57), (2, 2), (1, 67), (2, 18), (1, 23), (1, 36), (1, 33), (2, 81), (1, 55), (1, 18),
  (1, 23), (2, 41), (2, 14), (2, 44), (2, 69), (2, 83), (2, 18), (1, 37), (1, 43), (2, 38), (2, 27), (2, 21), (2, 46), (1, 95), (1, 23), (1, 80), (2, 47), (2, 56), (2, 48), (2, 31), (1, 37),
  (2, 39), (1, 80), (2, 29), (2, 45), (1, 42), (1, 7), (1, 2), (2, 67), (1, 61), (1, 61), (1, 73), (1, 82), (2, 44), (1, 23), (2, 86), (2, 17), (2, 48);


/* Question data */

INSERT INTO question (qs_id, qs_user_id, qs_name, qs_votes, qs_content) VALUES

  (1, 12, 'nulla. In tincidunt congue turpis. In', 98, 'sed pede. Cum sociis natoque penatibus et magnis dis parturient montes,  nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus.'),
  (2, 19, 'adipiscing fringilla,  porttitor vulputate,  posuere vulputate,  lacus. Cras interdum. Nunc', 97, 'non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem'),
  (3, 47, 'habitant morbi tristique senectus et', 61, 'egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est,  mollis non,  cursus non,  egestas a, '),
  (4, 26, 'varius. Nam porttitor scelerisque neque. Nullam nisl.', 13, 'nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est,  congue a,  aliquet vel,  vulputate eu,  odio. Phasellus at augue id ante dictum cursus.'),
  (5, 80, 'consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum', 100, 'Suspendisse sed dolor. Fusce mi lorem,  vehicula et,  rutrum eu,  ultrices sit amet,  risus. Donec nibh enim,  gravida sit amet,  dapibus id,  blandit at,  nisi. Cum sociis natoque penatibus'),
  (6, 13, 'sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum', 24, 'dolor quam,  elementum at,  egestas a,  scelerisque sed,  sapien. Nunc pulvinar arcu'),
  (7, 87, 'tempus,  lorem fringilla ornare placerat,  orci lacus vestibulum lorem, ', 56, 'et magnis dis parturient montes,  nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo'),
  (8, 96, 'quam vel sapien imperdiet ornare. In faucibus. Morbi', 63, 'dui. Cum sociis natoque penatibus et magnis dis parturient montes,  nascetur ridiculus mus.'),
  (9, 7, 'non enim commodo hendrerit. Donec porttitor tellus non magna. Nam', 87, 'Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis'),
  (10, 40, 'semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam', 1, 'blandit enim consequat purus. Maecenas libero est,  congue a,  aliquet vel,  vulputate eu,  odio. Phasellus'),
  (11, 26, 'bibendum. Donec felis orci,  adipiscing non,  luctus sit', 40, 'Class aptent taciti sociosqu ad litora torquent per conubia nostra,  per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec'),
  (12, 46, 'Phasellus dolor elit,  pellentesque a,  facilisis non,  bibendum', 38, 'aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non'),
  (13, 7, 'Nullam ut nisi a odio semper', 48, 'non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit,  pretium et,  rutrum non,  hendrerit id,  ante. Nunc mauris sapien,  cursus in, '),
  (14, 17, 'sollicitudin commodo ipsum. Suspendisse non leo.', 27, 'egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est,  mollis non,  cursus non,  egestas a,  dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper'),
  (15, 25, 'netus et malesuada fames ac', 34, 'aliquet odio. Etiam ligula tortor,  dictum eu,  placerat eget,  venenatis a,  magna. Lorem ipsum dolor sit amet,  consectetuer adipiscing elit. Etiam laoreet, '),
  (16, 65, 'velit in aliquet lobortis,  nisi nibh lacinia orci,  consectetuer euismod', 23, 'vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus.'),
  (17, 92, 'fringilla cursus purus. Nullam scelerisque neque', 35, 'nisi. Cum sociis natoque penatibus et magnis dis parturient montes,  nascetur'),
  (18, 98, 'purus. Nullam scelerisque neque sed sem egestas blandit. Nam', 23, 'in,  tempus eu,  ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec'),
  (19, 14, 'turpis nec mauris blandit mattis. Cras eget nisi dictum augue', 86, 'tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam,  elementum at, '),
  (20, 65, 'felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam', 71, 'tincidunt dui augue eu tellus. Phasellus elit pede,  malesuada vel,  venenatis vel,  faucibus id,  libero. Donec consectetuer mauris id sapien. Cras dolor dolor,  tempus non,  lacinia at,  iaculis quis, '),
  (21, 45, 'risus. Donec egestas. Duis ac arcu. Nunc', 62, 'eu dui. Cum sociis natoque penatibus et magnis dis parturient montes,  nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus.'),
  (22, 52, 'sodales purus,  in molestie tortor nibh sit', 92, 'Curabitur ut odio vel est tempor bibendum. Donec felis orci,  adipiscing non,  luctus sit amet,  faucibus ut, '),
  (23, 79, 'nibh dolor,  nonummy ac,  feugiat non,  lobortis quis, ', 37, 'mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et'),
  (24, 42, 'Phasellus libero mauris,  aliquam eu,  accumsan', 3, 'Nullam enim. Sed nulla ante,  iaculis nec,  eleifend non,  dapibus'),
  (25, 40, 'Integer vitae nibh. Donec est', 59, 'iaculis nec,  eleifend non,  dapibus rutrum,  justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget'),
  (26, 20, 'in,  cursus et,  eros. Proin ultrices. Duis volutpat nunc', 93, 'magnis dis parturient montes,  nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer'),
  (27, 93, 'massa non ante bibendum ullamcorper. Duis', 84, 'cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In'),
  (28, 37, 'Nullam enim. Sed nulla ante,  iaculis nec, ', 11, 'pede sagittis augue,  eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus'),
  (29, 32, 'elit pede,  malesuada vel,  venenatis vel, ', 65, 'dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna.'),
  (30, 22, 'In condimentum. Donec at arcu. Vestibulum ante', 56, 'feugiat tellus lorem eu metus. In lorem. Donec elementum,  lorem ut aliquam iaculis, '),
  (31, 22, 'diam lorem,  auctor quis,  tristique ac,  eleifend vitae,  erat. Vivamus', 35, 'sed,  facilisis vitae,  orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut'),
  (32, 99, 'vitae,  posuere at,  velit. Cras lorem', 18, 'odio a purus. Duis elementum,  dui quis accumsan convallis,  ante lectus convallis est,  vitae sodales nisi magna sed dui. Fusce aliquam,  enim nec tempus scelerisque,  lorem'),
  (33, 82, 'Nullam vitae diam. Proin dolor. Nulla', 2, 'Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor,  nonummy'),
  (34, 34, 'erat vitae risus. Duis a mi fringilla mi lacinia', 26, 'vitae velit egestas lacinia. Sed congue,  elit sed consequat auctor,  nunc nulla vulputate dui,  nec tempus mauris'),
  (35, 60, 'malesuada fames ac turpis egestas. Aliquam', 46, 'Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, '),
  (36, 36, 'nisl. Nulla eu neque pellentesque massa lobortis', 7, 'nisi magna sed dui. Fusce aliquam,  enim nec tempus scelerisque,  lorem ipsum sodales'),
  (37, 16, 'feugiat tellus lorem eu metus.', 11, 'Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor.'),
  (38, 70, 'cubilia Curae,  Donec tincidunt. Donec vitae erat vel', 76, 'Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede,  nonummy ut,  molestie in,  tempus eu,  ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus.'),
  (39, 56, 'Sed nulla ante,  iaculis nec,  eleifend non,  dapibus rutrum, ', 4, 'et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien,  gravida non,  sollicitudin a,  malesuada id,  erat. Etiam vestibulum'),
  (40, 54, 'hendrerit neque. In ornare sagittis felis. Donec tempor,  est ac', 59, 'tempus scelerisque,  lorem ipsum sodales purus,  in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse'),
  (41, 54, 'quam. Curabitur vel lectus. Cum sociis natoque penatibus et', 28, 'feugiat nec,  diam. Duis mi enim,  condimentum eget,  volutpat ornare,  facilisis eget,  ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede.'),
  (42, 3, 'ac mattis semper,  dui lectus rutrum urna,  nec', 98, 'vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis'),
  (43, 30, 'odio vel est tempor bibendum. Donec felis orci,  adipiscing', 21, 'erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam,  elementum'),
  (44, 1, 'sed turpis nec mauris blandit mattis. Cras eget nisi dictum', 26, 'quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra,  per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus.'),
  (45, 52, 'diam at pretium aliquet,  metus urna convallis erat,  eget tincidunt', 15, 'ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem,  auctor quis,  tristique ac,  eleifend vitae,  erat. Vivamus nisi. Mauris'),
  (46, 35, 'Aenean massa. Integer vitae nibh. Donec est mauris,  rhoncus', 20, 'Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante,  iaculis nec,  eleifend non,  dapibus'),
  (47, 74, 'mollis nec,  cursus a,  enim. Suspendisse aliquet,  sem', 69, 'diam. Sed diam lorem,  auctor quis,  tristique ac,  eleifend vitae,  erat. Vivamus nisi. Mauris nulla.'),
  (48, 16, 'lorem semper auctor. Mauris vel', 100, 'leo,  in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus,  diam at pretium aliquet,  metus'),
  (49, 91, 'Nunc laoreet lectus quis massa. Mauris vestibulum,  neque', 55, 'molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor,  est ac mattis semper,  dui lectus rutrum urna,  nec luctus felis purus ac tellus. Suspendisse'),
  (50, 74, 'Mauris vestibulum,  neque sed dictum eleifend,  nunc risus', 75, 'ac libero nec ligula consectetuer rhoncus. Nullam velit dui,  semper et,  lacinia vitae,  sodales at,  velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum'),
  (51, 89, 'Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem', 86, 'rutrum non,  hendrerit id,  ante. Nunc mauris sapien,  cursus in,  hendrerit consectetuer,  cursus et,  magna. Praesent'),
  (52, 71, 'nibh dolor,  nonummy ac,  feugiat non, ', 18, 'ut lacus. Nulla tincidunt,  neque vitae semper egestas,  urna justo faucibus lectus,  a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula'),
  (53, 51, 'tortor at risus. Nunc ac sem', 70, 'nunc,  ullamcorper eu,  euismod ac,  fermentum vel,  mauris. Integer sem elit,  pharetra ut,  pharetra sed,  hendrerit a,  arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus'),
  (54, 26, 'hendrerit a,  arcu. Sed et libero. Proin mi. Aliquam', 51, 'fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna,  malesuada vel,  convallis in,  cursus et,  eros. Proin ultrices.'),
  (55, 4, 'velit dui,  semper et,  lacinia vitae,  sodales at,  velit. Pellentesque', 66, 'odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, '),
  (56, 7, 'tempor diam dictum sapien. Aenean', 10, 'ullamcorper eu,  euismod ac,  fermentum vel,  mauris. Integer sem elit,  pharetra ut,  pharetra sed,  hendrerit a,  arcu.'),
  (57, 45, 'In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec', 54, 'laoreet ipsum. Curabitur consequat,  lectus sit amet luctus vulputate,  nisi sem semper erat,  in consectetuer ipsum nunc'),
  (58, 38, 'imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, ', 41, 'justo faucibus lectus,  a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet'),
  (59, 68, 'non ante bibendum ullamcorper. Duis cursus,  diam at', 86, 'ultricies ligula. Nullam enim. Sed nulla ante,  iaculis nec,  eleifend non,  dapibus rutrum,  justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit'),
  (60, 48, 'eu tellus. Phasellus elit pede, ', 30, 'tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede,  nonummy ut,  molestie in,  tempus'),
  (61, 26, 'Phasellus ornare. Fusce mollis. Duis sit amet', 43, 'enim. Sed nulla ante,  iaculis nec,  eleifend non,  dapibus rutrum,  justo. Praesent luctus. Curabitur egestas nunc'),
  (62, 55, 'Nulla tincidunt,  neque vitae semper egestas,  urna justo faucibus', 49, 'ac mattis velit justo nec ante. Maecenas mi felis,  adipiscing fringilla,  porttitor vulputate,  posuere vulputate,  lacus. Cras'),
  (63, 70, 'tellus sem mollis dui,  in sodales elit', 4, 'amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus,  diam'),
  (64, 26, 'massa. Quisque porttitor eros nec tellus. Nunc lectus pede,  ultrices', 38, 'eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum'),
  (65, 85, 'Quisque porttitor eros nec tellus. Nunc lectus pede, ', 22, 'neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt,  nunc ac mattis'),
  (66, 9, 'sit amet,  dapibus id,  blandit at,  nisi. Cum sociis natoque', 38, 'rutrum eu,  ultrices sit amet,  risus. Donec nibh enim,  gravida sit amet,  dapibus id,  blandit at,  nisi. Cum sociis'),
  (67, 38, 'diam luctus lobortis. Class aptent taciti sociosqu', 75, 'nunc ac mattis ornare,  lectus ante dictum mi,  ac mattis velit justo nec ante. Maecenas mi felis, '),
  (68, 17, 'vehicula aliquet libero. Integer in magna. Phasellus dolor elit,  pellentesque', 79, 'lacus. Nulla tincidunt,  neque vitae semper egestas,  urna justo faucibus lectus,  a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer'),
  (69, 26, 'eget magna. Suspendisse tristique neque venenatis lacus.', 60, 'iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec'),
  (70, 23, 'commodo hendrerit. Donec porttitor tellus', 88, 'consectetuer adipiscing elit. Etiam laoreet,  libero et tristique pellentesque,  tellus sem mollis dui,  in sodales elit erat vitae risus. Duis a mi'),
  (71, 21, 'amet ultricies sem magna nec quam. Curabitur vel', 98, 'a,  scelerisque sed,  sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris,  aliquam eu,  accumsan sed,  facilisis'),
  (72, 78, 'ornare sagittis felis. Donec tempor,  est', 21, 'erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue,  elit sed consequat auctor,  nunc nulla vulputate dui, '),
  (73, 52, 'odio vel est tempor bibendum. Donec felis orci,  adipiscing', 67, 'lobortis risus. In mi pede,  nonummy ut,  molestie in,  tempus eu,  ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris'),
  (74, 30, 'non,  sollicitudin a,  malesuada id,  erat. Etiam vestibulum massa', 51, 'augue eu tellus. Phasellus elit pede,  malesuada vel,  venenatis vel,  faucibus'),
  (75, 59, 'non,  luctus sit amet,  faucibus ut,  nulla. Cras', 10, 'dapibus rutrum,  justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus'),
  (76, 32, 'neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede', 8, 'sed pede nec ante blandit viverra. Donec tempus,  lorem fringilla ornare placerat,  orci lacus vestibulum lorem,  sit amet ultricies'),
  (77, 62, 'aliquet libero. Integer in magna. Phasellus dolor elit, ', 90, 'sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare,  libero at auctor ullamcorper,  nisl arcu iaculis enim,  sit amet ornare lectus justo eu arcu. Morbi sit amet'),
  (78, 34, 'feugiat tellus lorem eu metus. In lorem.', 48, 'fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet,  erat nonummy ultricies ornare,  elit elit fermentum risus,  at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu'),
  (79, 61, 'pede,  nonummy ut,  molestie in,  tempus eu,  ligula. Aenean euismod', 47, 'faucibus orci luctus et ultrices posuere cubilia Curae,  Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia.'),
  (80, 46, 'aliquet odio. Etiam ligula tortor,  dictum eu,  placerat', 12, 'pellentesque,  tellus sem mollis dui,  in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet,  erat'),
  (81, 51, 'dapibus gravida. Aliquam tincidunt,  nunc ac mattis', 17, 'arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien,  gravida'),
  (82, 85, 'vel quam dignissim pharetra. Nam ac nulla. In', 95, 'urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam,  elementum at,  egestas a,  scelerisque sed,  sapien. Nunc pulvinar arcu et'),
  (83, 59, 'tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam', 57, 'Vivamus nibh dolor,  nonummy ac,  feugiat non,  lobortis quis,  pede. Suspendisse dui. Fusce diam nunc,  ullamcorper eu,  euismod ac,  fermentum vel,  mauris. Integer sem elit,  pharetra ut,  pharetra'),
  (84, 70, 'dignissim lacus. Aliquam rutrum lorem', 32, 'Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia'),
  (85, 28, 'ut aliquam iaculis,  lacus pede', 92, 'cursus a,  enim. Suspendisse aliquet,  sem ut cursus luctus,  ipsum leo elementum sem,  vitae aliquam eros turpis non enim. Mauris quis turpis'),
  (86, 78, 'dolor. Fusce mi lorem,  vehicula et,  rutrum eu, ', 27, 'enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis'),
  (87, 66, 'enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis', 86, 'ac,  feugiat non,  lobortis quis,  pede. Suspendisse dui. Fusce diam nunc,  ullamcorper eu,  euismod ac,  fermentum vel,  mauris. Integer'),
  (88, 97, 'consequat auctor,  nunc nulla vulputate dui,  nec tempus', 69, 'sodales nisi magna sed dui. Fusce aliquam,  enim nec tempus scelerisque,  lorem ipsum sodales purus,  in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie'),
  (89, 86, 'adipiscing non,  luctus sit amet,  faucibus ut,  nulla.', 39, 'mattis ornare,  lectus ante dictum mi,  ac mattis velit justo nec ante. Maecenas mi'),
  (90, 57, 'mauris eu elit. Nulla facilisi. Sed neque. Sed eget', 45, 'tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare,  libero at auctor ullamcorper,  nisl'),
  (91, 8, 'Cras eget nisi dictum augue', 32, 'Suspendisse dui. Fusce diam nunc,  ullamcorper eu,  euismod ac,  fermentum vel,  mauris. Integer sem elit,  pharetra ut,  pharetra sed,  hendrerit a, '),
  (92, 11, 'arcu. Nunc mauris. Morbi non', 9, 'tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt,  nunc'),
  (93, 19, 'ante dictum cursus. Nunc mauris elit,  dictum eu, ', 30, 'consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh.'),
  (94, 32, 'Proin ultrices. Duis volutpat nunc sit amet', 50, 'metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate,  risus a ultricies adipiscing,  enim mi tempor lorem,  eget mollis lectus pede et risus.'),
  (95, 52, 'vitae aliquam eros turpis non enim. Mauris quis turpis vitae', 15, 'tincidunt dui augue eu tellus. Phasellus elit pede,  malesuada vel,  venenatis vel,  faucibus id,  libero. Donec consectetuer mauris id sapien.'),
  (96, 93, 'pharetra ut,  pharetra sed,  hendrerit a,  arcu. Sed', 68, 'eget,  venenatis a,  magna. Lorem ipsum dolor sit amet,  consectetuer adipiscing elit. Etiam laoreet,  libero et tristique pellentesque,  tellus'),
  (97, 90, 'euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate', 100, 'nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est,  mollis non,  cursus non,  egestas a, '),
  (98, 37, 'pretium aliquet,  metus urna convallis', 51, 'auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi'),
  (99, 43, 'et ultrices posuere cubilia Curae,  Phasellus ornare. Fusce', 82, 'neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor'),
  (100, 41, 'ante ipsum primis in faucibus orci luctus', 52, 'Phasellus libero mauris,  aliquam eu,  accumsan sed,  facilisis vitae,  orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames');


/* Comment data */

INSERT INTO comment (cm_id, cm_user_id, cm_question_id, cm_content) VALUES

  (1, 63, 9, 'Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus'),
  (2, 100, 10, 'Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada'),
  (3, 37, 7, 'vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris'),
  (4, 84, 10, 'ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra.'),
  (5, 43, 7, 'arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum,'),
  (6, 93, 2, 'amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis'),
  (7, 38, 4, 'eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus.'),
  (8, 28, 9, 'tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus.'),
  (9, 1, 3, 'adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus.'),
  (10, 99, 3, 'imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede.'),
  (11, 93, 9, 'libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et'),
  (12, 1, 9, 'eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus'),
  (13, 19, 9, 'nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis'),
  (14, 17, 4, 'eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque'),
  (15, 11, 3, 'nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut'),
  (16, 72, 2, 'in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa.'),
  (17, 95, 8, 'mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget'),
  (18, 33, 1, 'adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor'),
  (19, 77, 3, 'orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare'),
  (20, 9, 5, 'lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut,'),
  (21, 10, 4, 'sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum'),
  (22, 94, 6, 'magna tellus faucibus leo, in lobortis tellus justo sit amet nulla.'),
  (23, 69, 10, 'interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce'),
  (24, 78, 7, 'ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem,'),
  (25, 40, 6, 'lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at'),
  (26, 92, 8, 'ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula'),
  (27, 32, 2, 'vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis'),
  (28, 39, 3, 'ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem.'),
  (29, 66, 2, 'lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum.'),
  (30, 67, 10, 'morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer'),
  (31, 32, 8, 'Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat'),
  (32, 16, 9, 'gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi,'),
  (33, 9, 4, 'vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor,'),
  (34, 51, 4, 'ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus.'),
  (35, 98, 10, 'risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend'),
  (36, 76, 8, 'pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis.'),
  (37, 72, 5, 'vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae'),
  (38, 66, 8, 'natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec'),
  (39, 26, 9, 'non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in,'),
  (40, 82, 8, 'sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue'),
  (41, 87, 7, 'dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit'),
  (42, 42, 4, 'montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean'),
  (43, 45, 5, 'Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac'),
  (44, 76, 9, 'gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue'),
  (45, 14, 8, 'posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu'),
  (46, 32, 8, 'blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec'),
  (47, 55, 10, 'lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse'),
  (48, 25, 6, 'sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu.'),
  (49, 73, 5, 'Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla,'),
  (50, 25, 5, 'ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam'),
  (51, 17, 7, 'tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices'),
  (52, 11, 4, 'a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque'),
  (53, 91, 3, 'in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu'),
  (54, 55, 3, 'metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut'),
  (55, 4, 8, 'quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut,'),
  (56, 77, 1, 'eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam'),
  (57, 1, 9, 'mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at'),
  (58, 63, 7, 'arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit'),
  (59, 78, 8, 'Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim.'),
  (60, 52, 9, 'lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing'),
  (61, 17, 2, 'quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam'),
  (62, 96, 3, 'nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis.'),
  (63, 25, 1, 'eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et'),
  (64, 61, 7, 'aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem'),
  (65, 78, 9, 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel'),
  (66, 17, 8, 'a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam'),
  (67, 70, 8, 'odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec'),
  (68, 47, 7, 'turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna'),
  (69, 15, 6, 'luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id'),
  (70, 96, 6, 'scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus.'),
  (71, 67, 6, 'volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus'),
  (72, 7, 8, 'in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia'),
  (73, 79, 1, 'suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus'),
  (74, 24, 5, 'fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam'),
  (75, 20, 9, 'faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna.'),
  (76, 86, 3, 'egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin'),
  (77, 40, 9, 'Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut'),
  (78, 32, 7, 'eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus.'),
  (79, 98, 8, 'ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit.'),
  (80, 85, 2, 'magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper'),
  (81, 55, 3, 'mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus'),
  (82, 45, 10, 'feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada'),
  (83, 23, 3, 'sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta'),
  (84, 72, 5, 'dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et'),
  (85, 9, 8, 'malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque'),
  (86, 7, 5, 'mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet'),
  (87, 6, 8, 'eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis'),
  (88, 75, 3, 'nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci.'),
  (89, 99, 2, 'enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec'),
  (90, 75, 7, 'vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra.'),
  (91, 99, 8, 'ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis'),
  (92, 38, 7, 'augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada'),
  (93, 49, 2, 'nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat.'),
  (94, 19, 8, 'mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque.'),
  (95, 67, 1, 'fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus,'),
  (96, 70, 6, 'Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur'),
  (97, 58, 4, 'mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec,'),
  (98, 11, 10, 'ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus'),
  (99, 27, 3, 'elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh'),
  (100, 17, 5, 'tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy');


/* Answer Data */

INSERT INTO answer (asw_id, asw_user_id, asw_question_id, asw_votes, asw_content, asw_accepted) VALUES

  (1, 89, 1, 28, 'Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel,', 0),
  (2, 94, 1, 11, 'adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis', 0),
  (3, 52, 8, 36, 'Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim', 0),
  (4, 80, 6, 8, 'Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus', 1),
  (5, 88, 7, 13, 'montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, t arcu ac', 0),
  (6, 95, 8, 28, 'magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer', 1),
  (7, 75, 1, 14, 'odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum.', 0),
  (8, 1, 8, 25, 'Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id', 0),
  (9, 88, 5, 27, 'Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam', 0),
  (10, 93, 1, 1, 'velit eget laoreet posuere, enim nisl elementum purus, accumsan interdum libero', 0),
  (11, 15, 5, 30, 'Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam', 0),
  (12, 9, 3, 27, 'Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui.', 0),
  (13, 29, 5, 39, 'vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget', 1),
  (14, 8, 9, 39, 'Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu', 0),
  (15, 65, 2, 30, 'sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada.', 1),
  (16, 14, 5, 14, 'Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus', 1),
  (17, 51, 9, 24, 'sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae', 1),
  (18, 32, 2, 4, 'luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet,', 0),
  (19, 21, 10, 15, 'blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur', 0),
  (20, 95, 10, 24, 'In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum', 0),
  (21, 73, 7, 19, 'ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel', 0),
  (22, 95, 6, 36, 'pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque', 0),
  (23, 44, 5, 19, 'Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in', 0),
  (24, 73, 3, 4, 'lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam', 0),
  (25, 54, 3, 23, 'dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis.', 1),
  (26, 54, 7, 21, 'scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu', 0),
  (27, 74, 2, 38, 'consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui', 1),
  (28, 74, 1, 5, 'auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat,', 1),
  (29, 54, 7, 40, 'nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna', 1),
  (30, 2, 6, 22, 'Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi', 1),
  (31, 57, 17, 21, 'nonummy ac,  feugiat non,  lobortis quis,  pede. Suspendisse dui. Fusce diam nunc,  ullamcorper eu,  euismod ac,  fermentum vel,  mauris. Integer sem elit,  pharetra ut,  pharetra sed,  hendrerit a, ', 1),
  (32, 74, 91, 5, 'sed dolor. Fusce mi lorem,  vehicula et,  rutrum eu,  ultrices sit amet,  risus. Donec nibh enim,  gravida sit amet,  dapibus id,  blandit at,  nisi. Cum sociis natoque penatibus et', 0),
  (33, 16, 66, 7, 'sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero', 1),
  (34, 24, 92, 14, 'semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi.', 0),
  (35, 18, 90, 25, 'est. Nunc ullamcorper,  velit in aliquet lobortis,  nisi nibh lacinia orci,  consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna.', 1),
  (36, 50, 63, 36, 'tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum,  dui quis accumsan convallis,  ante lectus convallis est,  vitae sodales', 1),
  (37, 15, 21, 22, 'ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus', 1),
  (38, 1, 10, 32, 'tincidunt nibh. Phasellus nulla. Integer vulputate,  risus a ultricies adipiscing,  enim mi', 0),
  (39, 22, 45, 21, 'pede,  nonummy ut,  molestie in,  tempus eu,  ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit', 1),
  (40, 1, 52, 25, 'magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, ', 0),
  (41, 99, 82, 37, 'ac facilisis facilisis,  magna tellus faucibus leo,  in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, ', 1),
  (42, 80, 65, 9, 'ipsum. Suspendisse non leo. Vivamus nibh dolor,  nonummy ac,  feugiat non,  lobortis quis,  pede. Suspendisse dui. Fusce diam nunc,  ullamcorper', 0),
  (43, 68, 90, 37, 'Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris,  aliquam eu,  accumsan sed,  facilisis vitae,  orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi', 0),
  (44, 24, 33, 20, 'sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede,  ultrices a,  auctor non, ', 0),
  (45, 15, 79, 24, 'laoreet ipsum. Curabitur consequat,  lectus sit amet luctus vulputate,  nisi sem semper erat,  in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque', 0),
  (46, 38, 21, 36, 'augue id ante dictum cursus. Nunc mauris elit,  dictum eu, ', 0),
  (47, 86, 81, 23, 'et,  magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut', 1),
  (48, 77, 14, 23, 'lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien,  gravida', 0),
  (49, 23, 73, 20, 'et magnis dis parturient montes,  nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra.', 1),
  (50, 44, 41, 17, 'natoque penatibus et magnis dis parturient montes,  nascetur ridiculus mus. Proin', 0),
  (51, 1, 30, 12, 'eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum,  dui quis accumsan convallis,  ante lectus convallis est,  vitae sodales nisi magna sed dui. Fusce', 0),
  (52, 4, 92, 46, 'vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci,  adipiscing non,  luctus sit amet,  faucibus ut,  nulla. Cras eu tellus eu augue porttitor interdum.', 1),
  (53, 25, 61, 24, 'ultrices a,  auctor non,  feugiat nec,  diam. Duis mi enim,  condimentum eget,  volutpat ornare,  facilisis eget,  ipsum. Donec sollicitudin adipiscing ligula.', 0),
  (54, 47, 72, 20, 'sit amet diam eu dolor egestas rhoncus. Proin nisl sem,  consequat nec,  mollis', 1),
  (55, 61, 80, 41, 'mollis vitae,  posuere at,  velit. Cras lorem lorem,  luctus ut,  pellentesque eget,  dictum placerat,  augue. Sed molestie.', 1),
  (56, 82, 2, 33, 'penatibus et magnis dis parturient montes,  nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam', 0),
  (57, 92, 7, 29, 'urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien,  gravida non,  sollicitudin a,  malesuada id,  erat. Etiam vestibulum massa rutrum magna. Cras', 1),
  (58, 69, 22, 44, 'consectetuer,  cursus et,  magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit,  est ac', 1),
  (59, 78, 9, 27, 'convallis,  ante lectus convallis est,  vitae sodales nisi magna sed', 0),
  (60, 8, 89, 40, 'molestie pharetra nibh. Aliquam ornare,  libero at auctor ullamcorper,  nisl arcu iaculis enim,  sit amet ornare lectus justo eu arcu. Morbi sit', 0),
  (61, 67, 51, 43, 'Duis risus odio,  auctor vitae,  aliquet nec,  imperdiet nec,  leo. Morbi neque tellus,  imperdiet non,  vestibulum nec,  euismod in,  dolor. Fusce feugiat. Lorem ipsum dolor sit', 1),
  (62, 79, 93, 26, 'sem ut dolor dapibus gravida. Aliquam tincidunt,  nunc ac mattis ornare,  lectus ante dictum mi, ', 0),
  (63, 2, 90, 10, 'ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non', 1),
  (64, 96, 95, 48, 'sit amet,  consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam', 0),
  (65, 85, 13, 48, 'at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi', 0),
  (66, 75, 63, 8, 'velit justo nec ante. Maecenas mi felis,  adipiscing fringilla,  porttitor vulputate,  posuere vulputate,  lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse', 0),
  (67, 22, 90, 37, 'magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula', 0),
  (68, 44, 59, 37, 'vel est tempor bibendum. Donec felis orci,  adipiscing non,  luctus sit amet,  faucibus ut,  nulla. Cras eu tellus', 1),
  (69, 68, 61, 10, 'lobortis risus. In mi pede,  nonummy ut,  molestie in,  tempus eu,  ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus.', 1),
  (70, 69, 79, 34, 'Curae,  Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem,  consequat nec,  mollis vitae, ', 0),
  (71, 14, 5, 26, 'pretium aliquet,  metus urna convallis erat,  eget tincidunt dui augue eu tellus. Phasellus elit pede,  malesuada vel,  venenatis vel,  faucibus id,  libero. Donec', 0),
  (72, 62, 6, 32, 'Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor,  dictum eu,  placerat eget,  venenatis a, ', 0),
  (73, 67, 73, 35, 'mi tempor lorem,  eget mollis lectus pede et risus. Quisque libero', 1),
  (74, 11, 61, 24, 'eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit,  est ac facilisis', 1),
  (75, 94, 40, 43, 'sed dolor. Fusce mi lorem,  vehicula et,  rutrum eu,  ultrices sit amet,  risus. Donec nibh enim,  gravida sit', 1),
  (76, 88, 50, 19, 'dui. Cum sociis natoque penatibus et magnis dis parturient montes,  nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam', 0),
  (77, 20, 60, 33, 'Phasellus elit pede,  malesuada vel,  venenatis vel,  faucibus id,  libero. Donec consectetuer mauris id sapien. Cras dolor dolor,  tempus non,  lacinia at,  iaculis quis,  pede. Praesent eu', 0),
  (78, 89, 62, 31, 'commodo ipsum. Suspendisse non leo. Vivamus nibh dolor,  nonummy ac,  feugiat non,  lobortis quis,  pede. Suspendisse dui. Fusce diam nunc, ', 1),
  (79, 88, 91, 24, 'euismod in,  dolor. Fusce feugiat. Lorem ipsum dolor sit amet,  consectetuer adipiscing elit. Aliquam auctor,  velit', 1),
  (80, 89, 84, 16, 'nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et', 1),
  (81, 39, 34, 45, 'consectetuer adipiscing elit. Aliquam auctor,  velit eget laoreet posuere,  enim nisl elementum purus, ', 0),
  (82, 30, 56, 8, 'In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac', 0),
  (83, 83, 17, 4, 'enim. Sed nulla ante,  iaculis nec,  eleifend non,  dapibus rutrum,  justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras', 0),
  (84, 34, 17, 37, 'lobortis risus. In mi pede,  nonummy ut,  molestie in,  tempus eu,  ligula.', 0),
  (85, 19, 36, 16, 'Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec', 0),
  (86, 71, 60, 25, 'imperdiet nec,  leo. Morbi neque tellus,  imperdiet non,  vestibulum nec,  euismod in,  dolor. Fusce feugiat. Lorem ipsum dolor sit amet,  consectetuer adipiscing elit. Aliquam auctor,  velit eget laoreet', 1),
  (87, 89, 52, 1, 'Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit,  pellentesque a,  facilisis', 1),
  (88, 100, 28, 32, 'ultrices posuere cubilia Curae,  Phasellus ornare. Fusce mollis. Duis sit amet diam', 0),
  (89, 96, 92, 2, 'risus. In mi pede,  nonummy ut,  molestie in,  tempus eu,  ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus.', 1),
  (90, 39, 13, 16, 'lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare', 0),
  (91, 36, 77, 48, 'et tristique pellentesque,  tellus sem mollis dui,  in sodales elit erat vitae risus.', 1),
  (92, 86, 5, 27, 'velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod', 1),
  (93, 59, 44, 29, 'nec tellus. Nunc lectus pede,  ultrices a,  auctor non,  feugiat nec,  diam.', 0),
  (94, 86, 86, 25, 'Sed congue,  elit sed consequat auctor,  nunc nulla vulputate dui,  nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam', 0),
  (95, 41, 60, 34, 'dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis.', 0),
  (96, 37, 90, 23, 'sociis natoque penatibus et magnis dis parturient montes,  nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate', 0),
  (97, 53, 86, 11, 'velit. Cras lorem lorem,  luctus ut,  pellentesque eget,  dictum placerat, ', 0),
  (98, 97, 86, 43, 'quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem,  auctor quis,  tristique ac,  eleifend vitae,  erat. Vivamus nisi. Mauris nulla. Integer', 1),
  (99, 11, 79, 36, 'nonummy ultricies ornare,  elit elit fermentum risus,  at fringilla purus mauris a nunc. In at pede.', 1),
  (100, 61, 77, 27, 'mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui,  semper et,  lacinia', 1);

/* Tag data */

INSERT INTO tag (tag_id, tag_name, tag_desc) VALUES

  (1, 'at sem', 'Cras eu tellus eu augue'),
  (2, 'amet, risus.', 'adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu'),
  (3, 'nulla.', 'Duis sit amet diam eu dolor egestas rhoncus. Proin nisl'),
  (4, 'faucibus lectus,', 'magna'),
  (5, 'cursus', 'leo. Vivamus nibh dolor, nonummy ac,'),
  (6, 'tellus non', 'et magnis dis parturient montes, nascetur'),
  (7, 'et', 'penatibus et magnis dis parturient montes, nascetur'),
  (8, 'dolor', 'nulla magna, malesuada vel,'),
  (9, 'vulputate', 'dictum'),
  (10, 'lectus ante', 'diam nunc, ullamcorper eu, euismod'),
  (11, 'nostra,', 'Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque'),
  (12, 'Nunc quis', 'Donec fringilla. Donec feugiat metus sit amet'),
  (13, 'dui,', 'ac mattis velit justo'),
  (14, 'velit. Pellentesque', 'urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque'),
  (15, 'ante.', 'non lorem vitae odio sagittis semper. Nam tempor diam dictum'),
  (16, 'orci luctus', 'Nunc mauris elit, dictum eu,'),
  (17, 'Sed auctor', 'libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit'),
  (18, 'Lorem ipsum', 'nulla. Donec non justo. Proin'),
  (19, 'nonummy ipsum', 'dolor. Donec fringilla. Donec'),
  (20, 'et', 'lorem, sit amet ultricies sem magna nec'),
  (21, 'auctor, nunc', 'faucibus leo, in lobortis tellus'),
  (22, 'suscipit, est', 'eu nulla at'),
  (23, 'aliquet', 'volutpat. Nulla'),
  (24, 'Nunc mauris', 'sed, facilisis vitae, orci. Phasellus dapibus'),
  (25, 'neque', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet,'),
  (26, 'ornare lectus', 'eget, volutpat ornare, facilisis eget,'),
  (27, 'dignissim.', 'porta elit, a feugiat tellus lorem eu metus.'),
  (28, 'Mauris', 'tellus. Nunc lectus pede, ultrices a, auctor non, feugiat'),
  (29, 'et,', 'Quisque'),
  (30, 'dolor', 'egestas. Sed pharetra, felis eget varius ultrices,'),
  (31, 'dapibus', 'eu'),
  (32, 'imperdiet', 'lacus. Nulla tincidunt, neque'),
  (33, 'amet', 'magna et ipsum cursus vestibulum. Mauris magna.'),
  (34, 'felis', 'et risus. Quisque libero lacus, varius et, euismod'),
  (35, 'lacus. Ut', 'sapien, cursus in, hendrerit consectetuer, cursus et,'),
  (36, 'Integer id', 'diam luctus lobortis. Class aptent'),
  (37, 'vulputate,', 'erat.'),
  (38, 'lacus. Quisque', 'Duis elementum, dui quis'),
  (39, 'rutrum magna.', 'ipsum'),
  (40, 'nibh.', 'Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh'),
  (41, 'risus.', 'Etiam vestibulum massa'),
  (42, 'ut', 'lacinia'),
  (43, 'quis,', 'tristique neque venenatis lacus. Etiam bibendum fermentum'),
  (44, 'massa non', 'nibh. Aliquam'),
  (45, 'lacus pede', 'dis parturient montes, nascetur ridiculus'),
  (46, 'amet,', 'diam lorem, auctor quis, tristique ac, eleifend vitae,'),
  (47, 'ultricies', 'sem ut dolor dapibus gravida. Aliquam tincidunt,'),
  (48, 'mauris', 'risus, at fringilla purus mauris a nunc. In at'),
  (49, 'Curabitur egestas', 'Donec tempus, lorem fringilla ornare placerat,'),
  (50, 'Donec', 'vehicula aliquet libero. Integer in magna. Phasellus'),
  (51, 'id, ante.', 'dui quis'),
  (52, 'Cum sociis', 'montes, nascetur'),
  (53, 'metus facilisis', 'odio. Aliquam vulputate ullamcorper magna. Sed eu eros.'),
  (54, 'ipsum.', 'interdum ligula'),
  (55, 'vulputate', 'sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra,'),
  (56, 'molestie pharetra', 'a, malesuada id, erat. Etiam vestibulum massa rutrum magna.'),
  (57, 'felis.', 'lacus. Nulla tincidunt, neque vitae semper egestas, urna justo'),
  (58, 'Quisque', 'massa non ante bibendum ullamcorper. Duis cursus, diam at pretium'),
  (59, 'malesuada vel,', 'risus odio, auctor vitae, aliquet nec,'),
  (60, 'enim, condimentum', 'et magnis dis parturient montes,'),
  (61, 'elementum, lorem', 'Quisque ornare tortor at risus. Nunc ac'),
  (62, 'tristique', 'Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis,'),
  (63, 'Cras', 'Cras'),
  (64, 'enim.', 'felis. Donec tempor, est ac mattis semper, dui lectus'),
  (65, 'malesuada', 'lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod'),
  (66, 'eu tellus', 'eu metus. In'),
  (67, 'pede', 'dolor quam, elementum at, egestas a, scelerisque sed,'),
  (68, 'dolor dapibus', 'enim. Nunc ut erat. Sed nunc est, mollis'),
  (69, 'purus. Nullam', 'mauris blandit mattis. Cras eget nisi dictum augue'),
  (70, 'Suspendisse', 'tristique'),
  (71, 'gravida sit', 'metus. Vivamus euismod urna. Nullam lobortis'),
  (72, 'diam luctus', 'molestie pharetra'),
  (73, 'dolor', 'scelerisque sed, sapien. Nunc pulvinar arcu et pede.'),
  (74, 'penatibus', 'a, scelerisque'),
  (75, 'Nunc laoreet', 'vitae purus gravida'),
  (76, 'sociosqu', 'arcu. Vivamus sit amet risus. Donec'),
  (77, 'leo', 'vestibulum lorem, sit amet ultricies sem magna'),
  (78, 'sit amet', 'luctus'),
  (79, 'ac tellus.', 'Curabitur egestas nunc sed'),
  (80, 'nisi.', 'penatibus et magnis dis parturient'),
  (81, 'eu, ultrices', 'sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet'),
  (82, 'facilisis', 'rutrum lorem ac risus. Morbi metus. Vivamus'),
  (83, 'a', 'dolor dolor, tempus non, lacinia at, iaculis quis, pede.'),
  (84, 'risus', 'odio. Aliquam vulputate ullamcorper magna.'),
  (85, 'arcu.', 'non leo. Vivamus nibh dolor, nonummy ac, feugiat'),
  (86, 'mauris.', 'Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique'),
  (87, 'elit', 'nisi. Mauris nulla. Integer'),
  (88, 'pretium', 'adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras'),
  (89, 'Quisque porttitor', 'auctor, nunc nulla vulputate'),
  (90, 'Donec vitae', 'auctor velit. Aliquam nisl. Nulla eu neque pellentesque'),
  (91, 'nunc sed', 'sollicitudin commodo ipsum. Suspendisse non leo.'),
  (92, 'lacus', 'Sed eu nibh vulputate mauris sagittis placerat. Cras'),
  (93, 'enim non', 'a feugiat tellus lorem eu metus. In lorem. Donec elementum,'),
  (94, 'Pellentesque', 'arcu. Vestibulum ante ipsum primis in faucibus orci luctus et'),
  (95, 'Donec', 'eu tempor erat'),
  (96, 'ullamcorper,', 'urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque'),
  (97, 'quam', 'Curabitur vel lectus.'),
  (98, 'molestie tortor', 'accumsan sed, facilisis vitae,'),
  (99, 'ut quam', 'mauris ipsum porta elit, a feugiat'),
  (100, 'nec ligula', 'urna. Nunc quis arcu vel quam dignissim pharetra. Nam');


/* Question & Tag data */

INSERT INTO question_tag (qt_question_id, qt_tag_id) VALUES
  (9, 86), (6, 75), (8, 78), (3, 35), (9, 70), (1, 49),
  (5, 51), (1, 97), (2, 44), (3, 18), (6, 83), (6, 80),
  (10, 85), (5, 4), (2, 23), (7, 3), (3, 41), (8, 40),
  (1, 38), (7, 64), (4, 91), (10, 44), (1, 74), (10, 99),
  (2, 13), (6, 86), (8, 74), (8, 62), (6, 24), (6, 41),
  (9, 56), (2, 13), (5, 18), (8, 44), (8, 28), (2, 2),
  (2, 42), (3, 38), (5, 62), (4, 19), (9, 97), (9, 51),
  (6, 25), (3, 93), (2, 13), (8, 85), (3, 8), (10, 23),
  (9, 13), (1, 41), (7, 51), (2, 77), (6, 97), (4, 8),
  (8, 50), (5, 67), (4, 90), (4, 31), (8, 31), (10, 53),
  (6, 61), (5, 4), (8, 73), (10, 96), (3, 5), (10, 93),
  (7, 28), (9, 5), (6, 60), (2, 37), (10, 87), (5, 62),
  (3, 24), (7, 93);